# AUTOGENERATED by scripts/generate_sdk.py. Do not edit by hand.
# ruff: noqa
from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, Literal

from typing_extensions import Self

from datalens_sdk.runtime import (
    _BaseEditorNodeCreate,
    _BaseQLChartCreate,
    _BaseWizardChartCreate,
    _CombinedWizardChartCreate,
    _GeolayerWizardChartCreate,
    _MetricWizardChartCreate,
    _PivotWizardChartCreate,
    _ScatterWizardChartCreate,
    _TableWizardChartCreate,
)
from datalens_sdk.domain.entry_location import EntryLocation
from datalens_sdk.domain.chart_types import CombinedLayerType, DiscretePaletteId, FilterOperation, FunnelShape, GeoLayerFilter, GeoLayerType, GradientPaletteId, MeasureFormat, PaletteId, ShapeStyle
from datalens_sdk.domain.fields import (
    DatasetField,
    WizardFieldRef,
    WizardAggregatedMeasure,
    WizardHierarchy,
    WizardLocalField,
)
from datalens_sdk.domain.dataset import Dataset
from datalens_sdk.domain.ports import ChartOperations
from datalens_sdk.domain.ql_chart import QLColumn
from datalens_sdk.errors import NotSupportedError

INSTALLATION_EDITOR_NODE_TYPES: dict[str, frozenset[str]] = {
    'enterprise': frozenset(['advanced-chart_node', 'control_node', 'd3_node', 'markdown_node', 'table_node']),
    'yacloud': frozenset(['advanced-chart_node', 'control_node', 'd3_node', 'markdown_node', 'table_node']),
}

class WizardChartCreateFactory:
    def __init__(self, operations: ChartOperations) -> None:
        self._operations = operations

    def __getattr__(self, name: str) -> Any:
        raise NotSupportedError(
            'Wizard API v3 is unavailable because this installation has no generated Wizard structure'
        )

class AdvancedChartNodeNodeCreate(_BaseEditorNodeCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            wire_type='advanced-chart_node',
            name=name,
            location=location,
            operations=operations,
        )

    def controls(self, value: str) -> Self:
        return self._set_tab('controls', value)

    def meta(self, value: str) -> Self:
        return self._set_tab('meta', value)

    def params(self, value: str) -> Self:
        return self._set_tab('params', value)

    def prepare(self, value: str) -> Self:
        return self._set_tab('prepare', value)

    def sources(self, value: str) -> Self:
        return self._set_tab('sources', value)

class ControlNodeNodeCreate(_BaseEditorNodeCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            wire_type='control_node',
            name=name,
            location=location,
            operations=operations,
        )

    def controls(self, value: str) -> Self:
        return self._set_tab('controls', value)

    def meta(self, value: str) -> Self:
        return self._set_tab('meta', value)

    def params(self, value: str) -> Self:
        return self._set_tab('params', value)

    def sources(self, value: str) -> Self:
        return self._set_tab('sources', value)

class D3NodeNodeCreate(_BaseEditorNodeCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            wire_type='d3_node',
            name=name,
            location=location,
            operations=operations,
        )

    def config(self, value: str) -> Self:
        return self._set_tab('config', value)

    def controls(self, value: str) -> Self:
        return self._set_tab('controls', value)

    def meta(self, value: str) -> Self:
        return self._set_tab('meta', value)

    def params(self, value: str) -> Self:
        return self._set_tab('params', value)

    def prepare(self, value: str) -> Self:
        return self._set_tab('prepare', value)

    def sources(self, value: str) -> Self:
        return self._set_tab('sources', value)

class MarkdownNodeNodeCreate(_BaseEditorNodeCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            wire_type='markdown_node',
            name=name,
            location=location,
            operations=operations,
        )

    def controls(self, value: str) -> Self:
        return self._set_tab('controls', value)

    def meta(self, value: str) -> Self:
        return self._set_tab('meta', value)

    def params(self, value: str) -> Self:
        return self._set_tab('params', value)

    def prepare(self, value: str) -> Self:
        return self._set_tab('prepare', value)

    def sources(self, value: str) -> Self:
        return self._set_tab('sources', value)

class TableNodeNodeCreate(_BaseEditorNodeCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            wire_type='table_node',
            name=name,
            location=location,
            operations=operations,
        )

    def config(self, value: str) -> Self:
        return self._set_tab('config', value)

    def controls(self, value: str) -> Self:
        return self._set_tab('controls', value)

    def meta(self, value: str) -> Self:
        return self._set_tab('meta', value)

    def params(self, value: str) -> Self:
        return self._set_tab('params', value)

    def prepare(self, value: str) -> Self:
        return self._set_tab('prepare', value)

    def sources(self, value: str) -> Self:
        return self._set_tab('sources', value)

class EnterpriseEditorChartCreateFactory:
    def __init__(self, operations: ChartOperations) -> None:
        self._operations = operations

    def advanced_chart(self, *, name: str, location: EntryLocation) -> AdvancedChartNodeNodeCreate:
        return AdvancedChartNodeNodeCreate(name=name, location=location, operations=self._operations)

    def selector(self, *, name: str, location: EntryLocation) -> ControlNodeNodeCreate:
        return ControlNodeNodeCreate(name=name, location=location, operations=self._operations)

    def gravity_charts(self, *, name: str, location: EntryLocation) -> D3NodeNodeCreate:
        return D3NodeNodeCreate(name=name, location=location, operations=self._operations)

    def markdown(self, *, name: str, location: EntryLocation) -> MarkdownNodeNodeCreate:
        return MarkdownNodeNodeCreate(name=name, location=location, operations=self._operations)

    def table(self, *, name: str, location: EntryLocation) -> TableNodeNodeCreate:
        return TableNodeNodeCreate(name=name, location=location, operations=self._operations)

class YacloudEditorChartCreateFactory:
    def __init__(self, operations: ChartOperations) -> None:
        self._operations = operations

    def advanced_chart(self, *, name: str, location: EntryLocation) -> AdvancedChartNodeNodeCreate:
        return AdvancedChartNodeNodeCreate(name=name, location=location, operations=self._operations)

    def selector(self, *, name: str, location: EntryLocation) -> ControlNodeNodeCreate:
        return ControlNodeNodeCreate(name=name, location=location, operations=self._operations)

    def gravity_charts(self, *, name: str, location: EntryLocation) -> D3NodeNodeCreate:
        return D3NodeNodeCreate(name=name, location=location, operations=self._operations)

    def markdown(self, *, name: str, location: EntryLocation) -> MarkdownNodeNodeCreate:
        return MarkdownNodeNodeCreate(name=name, location=location, operations=self._operations)

    def table(self, *, name: str, location: EntryLocation) -> TableNodeNodeCreate:
        return TableNodeNodeCreate(name=name, location=location, operations=self._operations)

class QlAreaChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='area',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('x', columns)

    def y(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('y', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('colors', columns)

    def labels(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('labels', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlArea100pChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='area100p',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('x', columns)

    def y(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('y', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('colors', columns)

    def labels(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('labels', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlBarChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='bar',
            name=name,
            location=location,
            operations=operations,
        )

    def y(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('y', columns)

    def x(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('x', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('colors', columns)

    def labels(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('labels', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlBar100pChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='bar100p',
            name=name,
            location=location,
            operations=operations,
        )

    def y(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('y', columns)

    def x(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('x', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('colors', columns)

    def labels(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('labels', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlColumnChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='column',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('x', columns)

    def y(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('y', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('colors', columns)

    def labels(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('labels', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlColumn100pChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='column100p',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('x', columns)

    def y(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('y', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('colors', columns)

    def labels(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('labels', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlDonutChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='donut',
            name=name,
            location=location,
            operations=operations,
        )

    def dimensions(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('dimensions', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('colors', columns)

    def measures(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('measures', columns)

    def labels(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('labels', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlFlatTableChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='flatTable',
            name=name,
            location=location,
            operations=operations,
        )

    def flat_table_columns(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('flat_table_columns', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('colors', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlLineChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='line',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('x', columns)

    def y(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('y', columns)

    def y2(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('y2', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('colors', columns)

    def labels(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('labels', columns)

    def shapes(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('shapes', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlMetricChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='metric',
            name=name,
            location=location,
            operations=operations,
        )

    def measures(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('measures', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('colors', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlPieChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='pie',
            name=name,
            location=location,
            operations=operations,
        )

    def dimensions(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('dimensions', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('colors', columns)

    def measures(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('measures', columns)

    def labels(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('labels', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlScatterChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='scatter',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('x', columns)

    def y(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('y', columns)

    def points(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('points', columns)

    def size(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('size', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('colors', columns)

    def shapes(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('shapes', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlTreemapChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='treemap',
            name=name,
            location=location,
            operations=operations,
        )

    def dimensions(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('dimensions', columns)

    def measures(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('measures', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('colors', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QLChartCreateFactory:
    def __init__(self, operations: ChartOperations) -> None:
        self._operations = operations

    def area(self, *, name: str, location: EntryLocation) -> QlAreaChartCreate:
        return QlAreaChartCreate(name=name, location=location, operations=self._operations)

    def area_100p(self, *, name: str, location: EntryLocation) -> QlArea100pChartCreate:
        return QlArea100pChartCreate(name=name, location=location, operations=self._operations)

    def bar(self, *, name: str, location: EntryLocation) -> QlBarChartCreate:
        return QlBarChartCreate(name=name, location=location, operations=self._operations)

    def bar_100p(self, *, name: str, location: EntryLocation) -> QlBar100pChartCreate:
        return QlBar100pChartCreate(name=name, location=location, operations=self._operations)

    def column(self, *, name: str, location: EntryLocation) -> QlColumnChartCreate:
        return QlColumnChartCreate(name=name, location=location, operations=self._operations)

    def column_100p(self, *, name: str, location: EntryLocation) -> QlColumn100pChartCreate:
        return QlColumn100pChartCreate(name=name, location=location, operations=self._operations)

    def donut(self, *, name: str, location: EntryLocation) -> QlDonutChartCreate:
        return QlDonutChartCreate(name=name, location=location, operations=self._operations)

    def flat_table(self, *, name: str, location: EntryLocation) -> QlFlatTableChartCreate:
        return QlFlatTableChartCreate(name=name, location=location, operations=self._operations)

    def line(self, *, name: str, location: EntryLocation) -> QlLineChartCreate:
        return QlLineChartCreate(name=name, location=location, operations=self._operations)

    def indicator(self, *, name: str, location: EntryLocation) -> QlMetricChartCreate:
        return QlMetricChartCreate(name=name, location=location, operations=self._operations)

    def pie(self, *, name: str, location: EntryLocation) -> QlPieChartCreate:
        return QlPieChartCreate(name=name, location=location, operations=self._operations)

    def scatter(self, *, name: str, location: EntryLocation) -> QlScatterChartCreate:
        return QlScatterChartCreate(name=name, location=location, operations=self._operations)

    def treemap(self, *, name: str, location: EntryLocation) -> QlTreemapChartCreate:
        return QlTreemapChartCreate(name=name, location=location, operations=self._operations)
