# AUTOGENERATED by scripts/generate_sdk.py. Do not edit by hand.
# ruff: noqa
from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Literal

from typing_extensions import Self

from datalens_sdk.runtime import (
    _BaseEditorNodeCreate,
    _BaseQLChartCreate,
    _BaseWizardChartCreate,
    _CombinedWizardChartCreate,
    _GeolayerWizardChartCreate,
    _MetricWizardChartCreate,
    _PivotWizardChartCreate,
    _ScatterWizardChartCreate,
    _TableWizardChartCreate,
)
from datalens_sdk.domain.entry_location import EntryLocation
from datalens_sdk.domain.chart_types import CombinedLayerType, DiscretePaletteId, FilterOperation, FunnelShape, GeoLayerFilter, GeoLayerType, GradientPaletteId, MeasureFormat, PaletteId, ShapeStyle
from datalens_sdk.domain.fields import (
    DatasetField,
    WizardFieldRef,
    WizardAggregatedMeasure,
    WizardHierarchy,
    WizardLocalField,
)
from datalens_sdk.domain.dataset import Dataset
from datalens_sdk.domain.ports import ChartOperations
from datalens_sdk.domain.ql_chart import QLColumn

INSTALLATION_EDITOR_NODE_TYPES: dict[str, frozenset[str]] = {
    'enterprise': frozenset(['advanced-chart_node', 'control_node', 'd3_node', 'markdown_node', 'table_node']),
    'yacloud': frozenset(['advanced-chart_node', 'control_node', 'd3_node', 'markdown_node', 'table_node']),
}

class AreaWizardChartCreate(_BaseWizardChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            visualization_type='area',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('x', fields)

    def y(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('y', fields)

    def add_aggregated_measure(self, field: WizardAggregatedMeasure) -> Self:
        return self._add_aggregated_measure(field)

    def add_date_filter(self, field: WizardFieldRef, *, start: str, end: str, inclusive_end: bool = True) -> Self:
        return self._add_date_filter(field, start=start, end=end, inclusive_end=inclusive_end)

    def add_filter(self, field: WizardFieldRef, *, operation: FilterOperation, values: Sequence[str] = ()) -> Self:
        return self._add_filter(field, operation=operation, values=values)

    def add_hierarchy(self, hierarchy: WizardHierarchy) -> Self:
        return self._add_hierarchy(hierarchy)

    def add_local_field(self, field: WizardLocalField) -> Self:
        return self._add_local_field(field)

    def add_relative_date_filter(self, field: WizardFieldRef, *, start_offset: str, end_offset: str) -> Self:
        return self._add_relative_date_filter(field, start_offset=start_offset, end_offset=end_offset)

    def add_sort(self, field: WizardFieldRef, *, direction: Literal['asc', 'desc'] = 'asc') -> Self:
        return self._add_sort(field, direction=direction)

    def axis_scale(self, slot_name: Literal['y'], *, scale: Literal['linear', 'logarithmic'] = 'linear', mode: Literal['auto', 'manual'] = 'auto', min: str | None = None, max: str | None = None) -> Self:
        return self._axis_scale(slot_name, scale=scale, mode=mode, min=min, max=max)

    def axis_title(self, slot_name: Literal['x', 'y'], *, mode: Literal['off', 'manual', 'auto'], text: str = '') -> Self:
        return self._axis_title(slot_name, mode=mode, text=text)

    def axis_visibility(self, slot_name: Literal['x', 'y'], *, mode: Literal['hide', 'show']) -> Self:
        return self._set_slot_setting(slot_name, 'axisVisibility', mode)

    def chart_title(self, *, text: str = '', mode: Literal['show', 'hide'] = 'show') -> Self:
        return self._chart_title(text=text, mode=mode)

    def color_by_dimension(self, field: WizardFieldRef) -> Self:
        return self._color_by_dimension(field)

    def description(self, text: str) -> Self:
        return self._set_description(text)

    def grid(self, slot_name: Literal['x', 'y'], *, enabled: bool, step: int | None = None) -> Self:
        return self._grid(slot_name, enabled=enabled, step=step)

    def hide_labels(self, slot_name: Literal['x', 'y'], *, enabled: bool) -> Self:
        return self._set_slot_setting(slot_name, 'hideLabels', 'yes' if enabled else 'no')

    def label_mode(self, *, mode: Literal['absolute']) -> Self:
        return self._label_mode(mode=mode)

    def labels(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('labels', fields)

    def legend(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('legendMode', mode)

    def measure_format(self, field: WizardFieldRef, *, format: Literal['number', 'percent'] | None = None, precision: int | None = None, unit: Literal['auto', 'k', 'm', 'b', 't'] | None = None, prefix: str | None = None, postfix: str | None = None, show_rank_delimiter: bool | None = None) -> Self:
        return self._measure_format(field, format=format, precision=precision, unit=unit, prefix=prefix, postfix=postfix, show_rank_delimiter=show_rank_delimiter)

    def navigator(self, *, mode: Literal['show', 'hide']) -> Self:
        return self._navigator(mode=mode)

    def nulls_mode(self, slot_name: Literal['y'], *, mode: Literal['as-0', 'connect', 'ignore', 'use-previous']) -> Self:
        return self._set_slot_setting(slot_name, 'nulls', mode)

    def palette(self, *, id: PaletteId) -> Self:
        return self._palette(id=id)

    def segments(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('segments', fields)

    def sort(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('sort', fields)

    def tooltip(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('tooltip', mode)

    def tooltip_sum(self, *, enabled: bool) -> Self:
        return self._set_chart_setting('tooltipSum', 'on' if enabled else 'off')

class Area100pWizardChartCreate(_BaseWizardChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            visualization_type='area100p',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('x', fields)

    def y(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('y', fields)

    def add_aggregated_measure(self, field: WizardAggregatedMeasure) -> Self:
        return self._add_aggregated_measure(field)

    def add_date_filter(self, field: WizardFieldRef, *, start: str, end: str, inclusive_end: bool = True) -> Self:
        return self._add_date_filter(field, start=start, end=end, inclusive_end=inclusive_end)

    def add_filter(self, field: WizardFieldRef, *, operation: FilterOperation, values: Sequence[str] = ()) -> Self:
        return self._add_filter(field, operation=operation, values=values)

    def add_hierarchy(self, hierarchy: WizardHierarchy) -> Self:
        return self._add_hierarchy(hierarchy)

    def add_local_field(self, field: WizardLocalField) -> Self:
        return self._add_local_field(field)

    def add_relative_date_filter(self, field: WizardFieldRef, *, start_offset: str, end_offset: str) -> Self:
        return self._add_relative_date_filter(field, start_offset=start_offset, end_offset=end_offset)

    def add_sort(self, field: WizardFieldRef, *, direction: Literal['asc', 'desc'] = 'asc') -> Self:
        return self._add_sort(field, direction=direction)

    def axis_scale(self, slot_name: Literal['y'], *, scale: Literal['linear', 'logarithmic'] = 'linear', mode: Literal['auto', 'manual'] = 'auto', min: str | None = None, max: str | None = None) -> Self:
        return self._axis_scale(slot_name, scale=scale, mode=mode, min=min, max=max)

    def axis_title(self, slot_name: Literal['x', 'y'], *, mode: Literal['off', 'manual', 'auto'], text: str = '') -> Self:
        return self._axis_title(slot_name, mode=mode, text=text)

    def axis_visibility(self, slot_name: Literal['x', 'y'], *, mode: Literal['hide', 'show']) -> Self:
        return self._set_slot_setting(slot_name, 'axisVisibility', mode)

    def chart_title(self, *, text: str = '', mode: Literal['show', 'hide'] = 'show') -> Self:
        return self._chart_title(text=text, mode=mode)

    def color_by_dimension(self, field: WizardFieldRef) -> Self:
        return self._color_by_dimension(field)

    def description(self, text: str) -> Self:
        return self._set_description(text)

    def grid(self, slot_name: Literal['x', 'y'], *, enabled: bool, step: int | None = None) -> Self:
        return self._grid(slot_name, enabled=enabled, step=step)

    def hide_labels(self, slot_name: Literal['x', 'y'], *, enabled: bool) -> Self:
        return self._set_slot_setting(slot_name, 'hideLabels', 'yes' if enabled else 'no')

    def label_mode(self, *, mode: Literal['absolute', 'percent']) -> Self:
        return self._label_mode(mode=mode)

    def labels(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('labels', fields)

    def legend(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('legendMode', mode)

    def measure_format(self, field: WizardFieldRef, *, format: Literal['number', 'percent'] | None = None, precision: int | None = None, unit: Literal['auto', 'k', 'm', 'b', 't'] | None = None, prefix: str | None = None, postfix: str | None = None, show_rank_delimiter: bool | None = None) -> Self:
        return self._measure_format(field, format=format, precision=precision, unit=unit, prefix=prefix, postfix=postfix, show_rank_delimiter=show_rank_delimiter)

    def navigator(self, *, mode: Literal['show', 'hide']) -> Self:
        return self._navigator(mode=mode)

    def nulls_mode(self, slot_name: Literal['y'], *, mode: Literal['as-0', 'connect', 'ignore', 'use-previous']) -> Self:
        return self._set_slot_setting(slot_name, 'nulls', mode)

    def palette(self, *, id: PaletteId) -> Self:
        return self._palette(id=id)

    def segments(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('segments', fields)

    def sort(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('sort', fields)

    def tooltip(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('tooltip', mode)

    def tooltip_sum(self, *, enabled: bool) -> Self:
        return self._set_chart_setting('tooltipSum', 'on' if enabled else 'off')

class BarWizardChartCreate(_BaseWizardChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            visualization_type='bar',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('x', fields)

    def y(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('y', fields)

    def add_aggregated_measure(self, field: WizardAggregatedMeasure) -> Self:
        return self._add_aggregated_measure(field)

    def add_date_filter(self, field: WizardFieldRef, *, start: str, end: str, inclusive_end: bool = True) -> Self:
        return self._add_date_filter(field, start=start, end=end, inclusive_end=inclusive_end)

    def add_filter(self, field: WizardFieldRef, *, operation: FilterOperation, values: Sequence[str] = ()) -> Self:
        return self._add_filter(field, operation=operation, values=values)

    def add_hierarchy(self, hierarchy: WizardHierarchy) -> Self:
        return self._add_hierarchy(hierarchy)

    def add_local_field(self, field: WizardLocalField) -> Self:
        return self._add_local_field(field)

    def add_relative_date_filter(self, field: WizardFieldRef, *, start_offset: str, end_offset: str) -> Self:
        return self._add_relative_date_filter(field, start_offset=start_offset, end_offset=end_offset)

    def add_sort(self, field: WizardFieldRef, *, direction: Literal['asc', 'desc'] = 'asc') -> Self:
        return self._add_sort(field, direction=direction)

    def axis_scale(self, slot_name: Literal['x'], *, scale: Literal['linear', 'logarithmic'] = 'linear', mode: Literal['auto', 'manual'] = 'auto', min: str | None = None, max: str | None = None) -> Self:
        return self._axis_scale(slot_name, scale=scale, mode=mode, min=min, max=max)

    def axis_title(self, slot_name: Literal['x', 'y'], *, mode: Literal['off', 'manual', 'auto'], text: str = '') -> Self:
        return self._axis_title(slot_name, mode=mode, text=text)

    def axis_visibility(self, slot_name: Literal['x', 'y'], *, mode: Literal['hide', 'show']) -> Self:
        return self._set_slot_setting(slot_name, 'axisVisibility', mode)

    def chart_title(self, *, text: str = '', mode: Literal['show', 'hide'] = 'show') -> Self:
        return self._chart_title(text=text, mode=mode)

    def color_by_dimension(self, field: WizardFieldRef) -> Self:
        return self._color_by_dimension(field)

    def color_by_measure(self, field: WizardFieldRef, *, mode: Literal['2-point', '3-point'] | None = None, palette: GradientPaletteId | None = None, reversed: bool | None = None) -> Self:
        return self._color_by_measure(field, mode=mode, palette=palette, reversed=reversed)

    def color_by_measure_name(self, *, colors_map: Mapping[WizardFieldRef, str] | None = None) -> Self:
        return self._color_by_measure_name(colors_map=colors_map)

    def description(self, text: str) -> Self:
        return self._set_description(text)

    def grid(self, slot_name: Literal['x', 'y'], *, enabled: bool, step: int | None = None) -> Self:
        return self._grid(slot_name, enabled=enabled, step=step)

    def hide_labels(self, slot_name: Literal['x', 'y'], *, enabled: bool) -> Self:
        return self._set_slot_setting(slot_name, 'hideLabels', 'yes' if enabled else 'no')

    def label_mode(self, *, mode: Literal['absolute']) -> Self:
        return self._label_mode(mode=mode)

    def labels(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('labels', fields)

    def labels_position(self, *, mode: Literal['inside', 'outside', 'auto']) -> Self:
        return self._labels_position(mode=mode)

    def legend(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('legendMode', mode)

    def measure_format(self, field: WizardFieldRef, *, format: Literal['number', 'percent'] | None = None, precision: int | None = None, unit: Literal['auto', 'k', 'm', 'b', 't'] | None = None, prefix: str | None = None, postfix: str | None = None, show_rank_delimiter: bool | None = None) -> Self:
        return self._measure_format(field, format=format, precision=precision, unit=unit, prefix=prefix, postfix=postfix, show_rank_delimiter=show_rank_delimiter)

    def nulls_mode(self, slot_name: Literal['x'], *, mode: Literal['as-0', 'connect', 'ignore', 'use-previous']) -> Self:
        return self._set_slot_setting(slot_name, 'nulls', mode)

    def palette(self, *, id: PaletteId) -> Self:
        return self._palette(id=id)

    def sort(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('sort', fields)

    def tooltip(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('tooltip', mode)

    def tooltip_sum(self, *, enabled: bool) -> Self:
        return self._set_chart_setting('tooltipSum', 'on' if enabled else 'off')

class Bar100pWizardChartCreate(_BaseWizardChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            visualization_type='bar100p',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('x', fields)

    def y(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('y', fields)

    def add_aggregated_measure(self, field: WizardAggregatedMeasure) -> Self:
        return self._add_aggregated_measure(field)

    def add_date_filter(self, field: WizardFieldRef, *, start: str, end: str, inclusive_end: bool = True) -> Self:
        return self._add_date_filter(field, start=start, end=end, inclusive_end=inclusive_end)

    def add_filter(self, field: WizardFieldRef, *, operation: FilterOperation, values: Sequence[str] = ()) -> Self:
        return self._add_filter(field, operation=operation, values=values)

    def add_hierarchy(self, hierarchy: WizardHierarchy) -> Self:
        return self._add_hierarchy(hierarchy)

    def add_local_field(self, field: WizardLocalField) -> Self:
        return self._add_local_field(field)

    def add_relative_date_filter(self, field: WizardFieldRef, *, start_offset: str, end_offset: str) -> Self:
        return self._add_relative_date_filter(field, start_offset=start_offset, end_offset=end_offset)

    def add_sort(self, field: WizardFieldRef, *, direction: Literal['asc', 'desc'] = 'asc') -> Self:
        return self._add_sort(field, direction=direction)

    def axis_scale(self, slot_name: Literal['x'], *, scale: Literal['linear', 'logarithmic'] = 'linear', mode: Literal['auto', 'manual'] = 'auto', min: str | None = None, max: str | None = None) -> Self:
        return self._axis_scale(slot_name, scale=scale, mode=mode, min=min, max=max)

    def axis_title(self, slot_name: Literal['x', 'y'], *, mode: Literal['off', 'manual', 'auto'], text: str = '') -> Self:
        return self._axis_title(slot_name, mode=mode, text=text)

    def axis_visibility(self, slot_name: Literal['x', 'y'], *, mode: Literal['hide', 'show']) -> Self:
        return self._set_slot_setting(slot_name, 'axisVisibility', mode)

    def chart_title(self, *, text: str = '', mode: Literal['show', 'hide'] = 'show') -> Self:
        return self._chart_title(text=text, mode=mode)

    def color_by_dimension(self, field: WizardFieldRef) -> Self:
        return self._color_by_dimension(field)

    def description(self, text: str) -> Self:
        return self._set_description(text)

    def grid(self, slot_name: Literal['x', 'y'], *, enabled: bool, step: int | None = None) -> Self:
        return self._grid(slot_name, enabled=enabled, step=step)

    def hide_labels(self, slot_name: Literal['x', 'y'], *, enabled: bool) -> Self:
        return self._set_slot_setting(slot_name, 'hideLabels', 'yes' if enabled else 'no')

    def label_mode(self, *, mode: Literal['absolute', 'percent']) -> Self:
        return self._label_mode(mode=mode)

    def labels(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('labels', fields)

    def legend(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('legendMode', mode)

    def measure_format(self, field: WizardFieldRef, *, format: Literal['number', 'percent'] | None = None, precision: int | None = None, unit: Literal['auto', 'k', 'm', 'b', 't'] | None = None, prefix: str | None = None, postfix: str | None = None, show_rank_delimiter: bool | None = None) -> Self:
        return self._measure_format(field, format=format, precision=precision, unit=unit, prefix=prefix, postfix=postfix, show_rank_delimiter=show_rank_delimiter)

    def nulls_mode(self, slot_name: Literal['x'], *, mode: Literal['as-0', 'connect', 'ignore', 'use-previous']) -> Self:
        return self._set_slot_setting(slot_name, 'nulls', mode)

    def palette(self, *, id: PaletteId) -> Self:
        return self._palette(id=id)

    def sort(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('sort', fields)

    def tooltip(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('tooltip', mode)

    def tooltip_sum(self, *, enabled: bool) -> Self:
        return self._set_chart_setting('tooltipSum', 'on' if enabled else 'off')

class ColumnWizardChartCreate(_BaseWizardChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            visualization_type='column',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('x', fields)

    def y(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('y', fields)

    def add_aggregated_measure(self, field: WizardAggregatedMeasure) -> Self:
        return self._add_aggregated_measure(field)

    def add_date_filter(self, field: WizardFieldRef, *, start: str, end: str, inclusive_end: bool = True) -> Self:
        return self._add_date_filter(field, start=start, end=end, inclusive_end=inclusive_end)

    def add_filter(self, field: WizardFieldRef, *, operation: FilterOperation, values: Sequence[str] = ()) -> Self:
        return self._add_filter(field, operation=operation, values=values)

    def add_hierarchy(self, hierarchy: WizardHierarchy) -> Self:
        return self._add_hierarchy(hierarchy)

    def add_local_field(self, field: WizardLocalField) -> Self:
        return self._add_local_field(field)

    def add_relative_date_filter(self, field: WizardFieldRef, *, start_offset: str, end_offset: str) -> Self:
        return self._add_relative_date_filter(field, start_offset=start_offset, end_offset=end_offset)

    def add_sort(self, field: WizardFieldRef, *, direction: Literal['asc', 'desc'] = 'asc') -> Self:
        return self._add_sort(field, direction=direction)

    def axis_scale(self, slot_name: Literal['y'], *, scale: Literal['linear', 'logarithmic'] = 'linear', mode: Literal['auto', 'manual'] = 'auto', min: str | None = None, max: str | None = None) -> Self:
        return self._axis_scale(slot_name, scale=scale, mode=mode, min=min, max=max)

    def axis_title(self, slot_name: Literal['x', 'y'], *, mode: Literal['off', 'manual', 'auto'], text: str = '') -> Self:
        return self._axis_title(slot_name, mode=mode, text=text)

    def axis_visibility(self, slot_name: Literal['x', 'y'], *, mode: Literal['hide', 'show']) -> Self:
        return self._set_slot_setting(slot_name, 'axisVisibility', mode)

    def chart_title(self, *, text: str = '', mode: Literal['show', 'hide'] = 'show') -> Self:
        return self._chart_title(text=text, mode=mode)

    def color_by_dimension(self, field: WizardFieldRef) -> Self:
        return self._color_by_dimension(field)

    def color_by_measure(self, field: WizardFieldRef, *, mode: Literal['2-point', '3-point'] | None = None, palette: GradientPaletteId | None = None, reversed: bool | None = None) -> Self:
        return self._color_by_measure(field, mode=mode, palette=palette, reversed=reversed)

    def color_by_measure_name(self, *, colors_map: Mapping[WizardFieldRef, str] | None = None) -> Self:
        return self._color_by_measure_name(colors_map=colors_map)

    def description(self, text: str) -> Self:
        return self._set_description(text)

    def grid(self, slot_name: Literal['x', 'y'], *, enabled: bool, step: int | None = None) -> Self:
        return self._grid(slot_name, enabled=enabled, step=step)

    def hide_labels(self, slot_name: Literal['x', 'y'], *, enabled: bool) -> Self:
        return self._set_slot_setting(slot_name, 'hideLabels', 'yes' if enabled else 'no')

    def label_mode(self, *, mode: Literal['absolute']) -> Self:
        return self._label_mode(mode=mode)

    def labels(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('labels', fields)

    def labels_position(self, *, mode: Literal['inside', 'outside', 'auto']) -> Self:
        return self._labels_position(mode=mode)

    def legend(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('legendMode', mode)

    def measure_format(self, field: WizardFieldRef, *, format: Literal['number', 'percent'] | None = None, precision: int | None = None, unit: Literal['auto', 'k', 'm', 'b', 't'] | None = None, prefix: str | None = None, postfix: str | None = None, show_rank_delimiter: bool | None = None) -> Self:
        return self._measure_format(field, format=format, precision=precision, unit=unit, prefix=prefix, postfix=postfix, show_rank_delimiter=show_rank_delimiter)

    def navigator(self, *, mode: Literal['show', 'hide']) -> Self:
        return self._navigator(mode=mode)

    def nulls_mode(self, slot_name: Literal['y'], *, mode: Literal['as-0', 'connect', 'ignore', 'use-previous']) -> Self:
        return self._set_slot_setting(slot_name, 'nulls', mode)

    def palette(self, *, id: PaletteId) -> Self:
        return self._palette(id=id)

    def segments(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('segments', fields)

    def sort(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('sort', fields)

    def tooltip(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('tooltip', mode)

    def tooltip_sum(self, *, enabled: bool) -> Self:
        return self._set_chart_setting('tooltipSum', 'on' if enabled else 'off')

class Column100pWizardChartCreate(_BaseWizardChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            visualization_type='column100p',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('x', fields)

    def y(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('y', fields)

    def add_aggregated_measure(self, field: WizardAggregatedMeasure) -> Self:
        return self._add_aggregated_measure(field)

    def add_date_filter(self, field: WizardFieldRef, *, start: str, end: str, inclusive_end: bool = True) -> Self:
        return self._add_date_filter(field, start=start, end=end, inclusive_end=inclusive_end)

    def add_filter(self, field: WizardFieldRef, *, operation: FilterOperation, values: Sequence[str] = ()) -> Self:
        return self._add_filter(field, operation=operation, values=values)

    def add_hierarchy(self, hierarchy: WizardHierarchy) -> Self:
        return self._add_hierarchy(hierarchy)

    def add_local_field(self, field: WizardLocalField) -> Self:
        return self._add_local_field(field)

    def add_relative_date_filter(self, field: WizardFieldRef, *, start_offset: str, end_offset: str) -> Self:
        return self._add_relative_date_filter(field, start_offset=start_offset, end_offset=end_offset)

    def add_sort(self, field: WizardFieldRef, *, direction: Literal['asc', 'desc'] = 'asc') -> Self:
        return self._add_sort(field, direction=direction)

    def axis_scale(self, slot_name: Literal['y'], *, scale: Literal['linear', 'logarithmic'] = 'linear', mode: Literal['auto', 'manual'] = 'auto', min: str | None = None, max: str | None = None) -> Self:
        return self._axis_scale(slot_name, scale=scale, mode=mode, min=min, max=max)

    def axis_title(self, slot_name: Literal['x', 'y'], *, mode: Literal['off', 'manual', 'auto'], text: str = '') -> Self:
        return self._axis_title(slot_name, mode=mode, text=text)

    def axis_visibility(self, slot_name: Literal['x', 'y'], *, mode: Literal['hide', 'show']) -> Self:
        return self._set_slot_setting(slot_name, 'axisVisibility', mode)

    def chart_title(self, *, text: str = '', mode: Literal['show', 'hide'] = 'show') -> Self:
        return self._chart_title(text=text, mode=mode)

    def color_by_dimension(self, field: WizardFieldRef) -> Self:
        return self._color_by_dimension(field)

    def description(self, text: str) -> Self:
        return self._set_description(text)

    def grid(self, slot_name: Literal['x', 'y'], *, enabled: bool, step: int | None = None) -> Self:
        return self._grid(slot_name, enabled=enabled, step=step)

    def hide_labels(self, slot_name: Literal['x', 'y'], *, enabled: bool) -> Self:
        return self._set_slot_setting(slot_name, 'hideLabels', 'yes' if enabled else 'no')

    def label_mode(self, *, mode: Literal['absolute', 'percent']) -> Self:
        return self._label_mode(mode=mode)

    def labels(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('labels', fields)

    def legend(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('legendMode', mode)

    def measure_format(self, field: WizardFieldRef, *, format: Literal['number', 'percent'] | None = None, precision: int | None = None, unit: Literal['auto', 'k', 'm', 'b', 't'] | None = None, prefix: str | None = None, postfix: str | None = None, show_rank_delimiter: bool | None = None) -> Self:
        return self._measure_format(field, format=format, precision=precision, unit=unit, prefix=prefix, postfix=postfix, show_rank_delimiter=show_rank_delimiter)

    def navigator(self, *, mode: Literal['show', 'hide']) -> Self:
        return self._navigator(mode=mode)

    def nulls_mode(self, slot_name: Literal['y'], *, mode: Literal['as-0', 'connect', 'ignore', 'use-previous']) -> Self:
        return self._set_slot_setting(slot_name, 'nulls', mode)

    def palette(self, *, id: PaletteId) -> Self:
        return self._palette(id=id)

    def segments(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('segments', fields)

    def sort(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('sort', fields)

    def tooltip(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('tooltip', mode)

    def tooltip_sum(self, *, enabled: bool) -> Self:
        return self._set_chart_setting('tooltipSum', 'on' if enabled else 'off')

class CombinedChartWizardChartCreate(_CombinedWizardChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            visualization_type='combined-chart',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._combined_x(fields)

    def add_layer(self, layer_type: CombinedLayerType, *, y: WizardFieldRef | None = None, y2: WizardFieldRef | None = None, name: str | None = None) -> Self:
        return self._combined_add_layer(layer_type, y=y, y2=y2, name=name)

    def add_aggregated_measure(self, field: WizardAggregatedMeasure) -> Self:
        return self._add_aggregated_measure(field)

    def add_date_filter(self, field: WizardFieldRef, *, start: str, end: str, inclusive_end: bool = True) -> Self:
        return self._add_date_filter(field, start=start, end=end, inclusive_end=inclusive_end)

    def add_filter(self, field: WizardFieldRef, *, operation: FilterOperation, values: Sequence[str] = ()) -> Self:
        return self._add_filter(field, operation=operation, values=values)

    def add_local_field(self, field: WizardLocalField) -> Self:
        return self._add_local_field(field)

    def add_relative_date_filter(self, field: WizardFieldRef, *, start_offset: str, end_offset: str) -> Self:
        return self._add_relative_date_filter(field, start_offset=start_offset, end_offset=end_offset)

    def add_sort(self, field: WizardFieldRef, *, direction: Literal['asc', 'desc'] = 'asc') -> Self:
        return self._add_sort(field, direction=direction)

    def chart_title(self, *, text: str = '', mode: Literal['show', 'hide'] = 'show') -> Self:
        return self._chart_title(text=text, mode=mode)

    def description(self, text: str) -> Self:
        return self._set_description(text)

    def labels(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('labels', fields)

    def labels_position(self, *, mode: Literal['inside', 'outside', 'auto']) -> Self:
        return self._labels_position(mode=mode)

    def legend(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('legendMode', mode)

    def measure_format(self, field: WizardFieldRef, *, format: Literal['number', 'percent'] | None = None, precision: int | None = None, unit: Literal['auto', 'k', 'm', 'b', 't'] | None = None, prefix: str | None = None, postfix: str | None = None, show_rank_delimiter: bool | None = None) -> Self:
        return self._measure_format(field, format=format, precision=precision, unit=unit, prefix=prefix, postfix=postfix, show_rank_delimiter=show_rank_delimiter)

    def sort(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('sort', fields)

    def tooltip(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('tooltip', mode)

class DonutWizardChartCreate(_BaseWizardChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            visualization_type='donut',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('dimensions', fields)

    def y(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('measures', fields)

    def add_aggregated_measure(self, field: WizardAggregatedMeasure) -> Self:
        return self._add_aggregated_measure(field)

    def add_date_filter(self, field: WizardFieldRef, *, start: str, end: str, inclusive_end: bool = True) -> Self:
        return self._add_date_filter(field, start=start, end=end, inclusive_end=inclusive_end)

    def add_filter(self, field: WizardFieldRef, *, operation: FilterOperation, values: Sequence[str] = ()) -> Self:
        return self._add_filter(field, operation=operation, values=values)

    def add_local_field(self, field: WizardLocalField) -> Self:
        return self._add_local_field(field)

    def add_relative_date_filter(self, field: WizardFieldRef, *, start_offset: str, end_offset: str) -> Self:
        return self._add_relative_date_filter(field, start_offset=start_offset, end_offset=end_offset)

    def add_sort(self, field: WizardFieldRef, *, direction: Literal['asc', 'desc'] = 'asc') -> Self:
        return self._add_sort(field, direction=direction)

    def chart_title(self, *, text: str = '', mode: Literal['show', 'hide'] = 'show') -> Self:
        return self._chart_title(text=text, mode=mode)

    def color_by_dimension(self, field: WizardFieldRef) -> Self:
        return self._color_by_dimension(field)

    def description(self, text: str) -> Self:
        return self._set_description(text)

    def label_mode(self, *, mode: Literal['absolute', 'percent']) -> Self:
        return self._label_mode(mode=mode)

    def labels(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('labels', fields)

    def legend(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('legendMode', mode)

    def measure_format(self, field: WizardFieldRef, *, format: Literal['number', 'percent'] | None = None, precision: int | None = None, unit: Literal['auto', 'k', 'm', 'b', 't'] | None = None, prefix: str | None = None, postfix: str | None = None, show_rank_delimiter: bool | None = None) -> Self:
        return self._measure_format(field, format=format, precision=precision, unit=unit, prefix=prefix, postfix=postfix, show_rank_delimiter=show_rank_delimiter)

    def palette(self, *, id: PaletteId) -> Self:
        return self._palette(id=id)

    def sort(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('sort', fields)

    def tooltip(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('tooltip', mode)

    def totals(self, *, enabled: bool) -> Self:
        return self._set_chart_setting('totals', 'on' if enabled else 'off')

class FlatTableWizardChartCreate(_TableWizardChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            visualization_type='flatTable',
            name=name,
            location=location,
            operations=operations,
        )

    def columns(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('columns', fields)

    def add_aggregated_measure(self, field: WizardAggregatedMeasure) -> Self:
        return self._add_aggregated_measure(field)

    def add_date_filter(self, field: WizardFieldRef, *, start: str, end: str, inclusive_end: bool = True) -> Self:
        return self._add_date_filter(field, start=start, end=end, inclusive_end=inclusive_end)

    def add_filter(self, field: WizardFieldRef, *, operation: FilterOperation, values: Sequence[str] = ()) -> Self:
        return self._add_filter(field, operation=operation, values=values)

    def add_hierarchy(self, hierarchy: WizardHierarchy) -> Self:
        return self._add_hierarchy(hierarchy)

    def add_local_field(self, field: WizardLocalField) -> Self:
        return self._add_local_field(field)

    def add_relative_date_filter(self, field: WizardFieldRef, *, start_offset: str, end_offset: str) -> Self:
        return self._add_relative_date_filter(field, start_offset=start_offset, end_offset=end_offset)

    def add_sort(self, field: WizardFieldRef, *, direction: Literal['asc', 'desc'] = 'asc') -> Self:
        return self._add_sort(field, direction=direction)

    def chart_title(self, *, text: str = '', mode: Literal['show', 'hide'] = 'show') -> Self:
        return self._chart_title(text=text, mode=mode)

    def color_by_measure(self, field: WizardFieldRef, *, mode: Literal['2-point', '3-point'] | None = None, palette: GradientPaletteId | None = None, reversed: bool | None = None) -> Self:
        return self._color_by_measure(field, mode=mode, palette=palette, reversed=reversed)

    def column_background(self, field: WizardFieldRef, *, mode: Literal['2-point', '3-point'] = '3-point', palette: GradientPaletteId = 'red-orange-green', thresholds: tuple[float, ...] | None = None, reversed: bool = False) -> Self:
        return self._column_background(field, mode=mode, palette=palette, thresholds=thresholds, reversed=reversed)

    def column_bars(self, field: WizardFieldRef, *, enabled: bool = True, color_type: Literal['one-color', 'two-color', 'gradient'] = 'one-color', color: str | None = None, palette: DiscretePaletteId | None = None, color_index: int | None = None, color_positive: str | None = None, color_negative: str | None = None, positive_color_index: int | None = None, negative_color_index: int | None = None, gradient_palette: GradientPaletteId | None = None, gradient_type: Literal['2-point', '3-point'] = '2-point', reversed: bool = False, show_labels: bool = True, show_in_totals: bool = False, align: Literal['default', 'left', 'right'] = 'default') -> Self:
        return self._column_bars(field, enabled=enabled, color_type=color_type, color=color, palette=palette, color_index=color_index, color_positive=color_positive, color_negative=color_negative, positive_color_index=positive_color_index, negative_color_index=negative_color_index, gradient_palette=gradient_palette, gradient_type=gradient_type, reversed=reversed, show_labels=show_labels, show_in_totals=show_in_totals, align=align)

    def column_title(self, field: WizardFieldRef, *, title: str) -> Self:
        return self._column_title(field, title=title)

    def description(self, text: str) -> Self:
        return self._set_description(text)

    def freeze_columns(self, *, count: int = 1) -> Self:
        return self._freeze_columns(count=count)

    def measure_format(self, field: WizardFieldRef, *, format: Literal['number', 'percent'] | None = None, precision: int | None = None, unit: Literal['auto', 'k', 'm', 'b', 't'] | None = None, prefix: str | None = None, postfix: str | None = None, show_rank_delimiter: bool | None = None) -> Self:
        return self._measure_format(field, format=format, precision=precision, unit=unit, prefix=prefix, postfix=postfix, show_rank_delimiter=show_rank_delimiter)

    def pagination(self, *, enabled: bool, limit: int = 100) -> Self:
        return self._pagination(enabled=enabled, limit=limit)

    def palette(self, *, id: PaletteId) -> Self:
        return self._palette(id=id)

    def sort(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('sort', fields)

    def table_size(self, *, size: Literal['s', 'm', 'l']) -> Self:
        return self._table_size(size=size)

    def totals(self, *, enabled: bool) -> Self:
        return self._set_chart_setting('totals', 'on' if enabled else 'off')

class FunnelWizardChartCreate(_BaseWizardChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            visualization_type='funnel',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('dimensions', fields)

    def y(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('measures', fields)

    def add_aggregated_measure(self, field: WizardAggregatedMeasure) -> Self:
        return self._add_aggregated_measure(field)

    def add_date_filter(self, field: WizardFieldRef, *, start: str, end: str, inclusive_end: bool = True) -> Self:
        return self._add_date_filter(field, start=start, end=end, inclusive_end=inclusive_end)

    def add_filter(self, field: WizardFieldRef, *, operation: FilterOperation, values: Sequence[str] = ()) -> Self:
        return self._add_filter(field, operation=operation, values=values)

    def add_local_field(self, field: WizardLocalField) -> Self:
        return self._add_local_field(field)

    def add_relative_date_filter(self, field: WizardFieldRef, *, start_offset: str, end_offset: str) -> Self:
        return self._add_relative_date_filter(field, start_offset=start_offset, end_offset=end_offset)

    def add_sort(self, field: WizardFieldRef, *, direction: Literal['asc', 'desc'] = 'asc') -> Self:
        return self._add_sort(field, direction=direction)

    def chart_title(self, *, text: str = '', mode: Literal['show', 'hide'] = 'show') -> Self:
        return self._chart_title(text=text, mode=mode)

    def color_by_dimension(self, field: WizardFieldRef) -> Self:
        return self._color_by_dimension(field)

    def description(self, text: str) -> Self:
        return self._set_description(text)

    def label_mode(self, *, mode: Literal['absolute', 'percent']) -> Self:
        return self._label_mode(mode=mode)

    def labels(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('labels', fields)

    def labels_position(self, *, mode: Literal['inside', 'outside', 'auto']) -> Self:
        return self._labels_position(mode=mode)

    def legend(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('legendMode', mode)

    def measure_format(self, field: WizardFieldRef, *, format: Literal['number', 'percent'] | None = None, precision: int | None = None, unit: Literal['auto', 'k', 'm', 'b', 't'] | None = None, prefix: str | None = None, postfix: str | None = None, show_rank_delimiter: bool | None = None) -> Self:
        return self._measure_format(field, format=format, precision=precision, unit=unit, prefix=prefix, postfix=postfix, show_rank_delimiter=show_rank_delimiter)

    def palette(self, *, id: PaletteId) -> Self:
        return self._palette(id=id)

    def shape(self, *, value: FunnelShape) -> Self:
        return self._funnel_shape(value=value)

    def sort(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('sort', fields)

    def tooltip(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('tooltip', mode)

    def tooltip_percentage_base(self, *, mode: Literal['auto', 'first', 'previous']) -> Self:
        return self._set_chart_setting('tooltipPercentageBase', mode)

class GeolayerWizardChartCreate(_GeolayerWizardChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            visualization_type='geolayer',
            name=name,
            location=location,
            operations=operations,
        )

    def add_dataset(self, dataset: Dataset) -> Self:
        return self._geo_add_dataset(dataset)

    def add_layer(self, layer_type: GeoLayerType, *, geopoint: WizardFieldRef | None = None, polygon: WizardFieldRef | None = None, polyline: WizardFieldRef | None = None, grouping: WizardFieldRef | None = None, size: WizardFieldRef | None = None, color: WizardFieldRef | None = None, color_mode: Literal['2-point', '3-point'] | None = None, color_palette: GradientPaletteId | None = None, color_reversed: bool | None = None, filters: Sequence[GeoLayerFilter] = (), tooltips: Sequence[WizardFieldRef] = (), labels: Sequence[WizardFieldRef] = (), sort_by: WizardFieldRef | None = None, sort_direction: Literal['asc', 'desc'] = 'asc', alpha: int = 80, name: str | None = None, dataset: Dataset | None = None) -> Self:
        return self._geo_add_layer(layer_type, geopoint=geopoint, polygon=polygon, polyline=polyline, grouping=grouping, size=size, color=color, color_mode=color_mode, color_palette=color_palette, color_reversed=color_reversed, filters=filters, tooltips=tooltips, labels=labels, sort_by=sort_by, sort_direction=sort_direction, alpha=alpha, name=name, dataset=dataset)

    def map_center(self, *, lat: float, lon: float, zoom: int | None = None) -> Self:
        return self._map_center(lat=lat, lon=lon, zoom=zoom)

    def add_aggregated_measure(self, field: WizardAggregatedMeasure) -> Self:
        return self._add_aggregated_measure(field)

    def add_date_filter(self, field: WizardFieldRef, *, start: str, end: str, inclusive_end: bool = True) -> Self:
        return self._add_date_filter(field, start=start, end=end, inclusive_end=inclusive_end)

    def add_filter(self, field: WizardFieldRef, *, operation: FilterOperation, values: Sequence[str] = ()) -> Self:
        return self._add_filter(field, operation=operation, values=values)

    def add_local_field(self, field: WizardLocalField) -> Self:
        return self._add_local_field(field)

    def add_relative_date_filter(self, field: WizardFieldRef, *, start_offset: str, end_offset: str) -> Self:
        return self._add_relative_date_filter(field, start_offset=start_offset, end_offset=end_offset)

    def chart_title(self, *, text: str = '', mode: Literal['show', 'hide'] = 'show') -> Self:
        return self._chart_title(text=text, mode=mode)

    def description(self, text: str) -> Self:
        return self._set_description(text)

    def labels(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('labels', fields)

    def legend(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('legendMode', mode)

    def measure_format(self, field: WizardFieldRef, *, format: Literal['number', 'percent'] | None = None, precision: int | None = None, unit: Literal['auto', 'k', 'm', 'b', 't'] | None = None, prefix: str | None = None, postfix: str | None = None, show_rank_delimiter: bool | None = None) -> Self:
        return self._measure_format(field, format=format, precision=precision, unit=unit, prefix=prefix, postfix=postfix, show_rank_delimiter=show_rank_delimiter)

class LineWizardChartCreate(_BaseWizardChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            visualization_type='line',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('x', fields)

    def y(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('y', fields)

    def y2(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('y2', fields)

    def add_aggregated_measure(self, field: WizardAggregatedMeasure) -> Self:
        return self._add_aggregated_measure(field)

    def add_date_filter(self, field: WizardFieldRef, *, start: str, end: str, inclusive_end: bool = True) -> Self:
        return self._add_date_filter(field, start=start, end=end, inclusive_end=inclusive_end)

    def add_filter(self, field: WizardFieldRef, *, operation: FilterOperation, values: Sequence[str] = ()) -> Self:
        return self._add_filter(field, operation=operation, values=values)

    def add_hierarchy(self, hierarchy: WizardHierarchy) -> Self:
        return self._add_hierarchy(hierarchy)

    def add_local_field(self, field: WizardLocalField) -> Self:
        return self._add_local_field(field)

    def add_relative_date_filter(self, field: WizardFieldRef, *, start_offset: str, end_offset: str) -> Self:
        return self._add_relative_date_filter(field, start_offset=start_offset, end_offset=end_offset)

    def add_sort(self, field: WizardFieldRef, *, direction: Literal['asc', 'desc'] = 'asc') -> Self:
        return self._add_sort(field, direction=direction)

    def axis_scale(self, slot_name: Literal['y', 'y2'], *, scale: Literal['linear', 'logarithmic'] = 'linear', mode: Literal['auto', 'manual'] = 'auto', min: str | None = None, max: str | None = None) -> Self:
        return self._axis_scale(slot_name, scale=scale, mode=mode, min=min, max=max)

    def axis_title(self, slot_name: Literal['x', 'y', 'y2'], *, mode: Literal['off', 'manual', 'auto'], text: str = '') -> Self:
        return self._axis_title(slot_name, mode=mode, text=text)

    def axis_visibility(self, slot_name: Literal['x', 'y', 'y2'], *, mode: Literal['hide', 'show']) -> Self:
        return self._set_slot_setting(slot_name, 'axisVisibility', mode)

    def chart_title(self, *, text: str = '', mode: Literal['show', 'hide'] = 'show') -> Self:
        return self._chart_title(text=text, mode=mode)

    def color_by_dimension(self, field: WizardFieldRef) -> Self:
        return self._color_by_dimension(field)

    def color_by_measure_name(self, *, colors_map: Mapping[WizardFieldRef, str] | None = None) -> Self:
        return self._color_by_measure_name(colors_map=colors_map)

    def description(self, text: str) -> Self:
        return self._set_description(text)

    def grid(self, slot_name: Literal['x', 'y', 'y2'], *, enabled: bool, step: int | None = None) -> Self:
        return self._grid(slot_name, enabled=enabled, step=step)

    def hide_labels(self, slot_name: Literal['x', 'y', 'y2'], *, enabled: bool) -> Self:
        return self._set_slot_setting(slot_name, 'hideLabels', 'yes' if enabled else 'no')

    def label_mode(self, *, mode: Literal['absolute']) -> Self:
        return self._label_mode(mode=mode)

    def labels(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('labels', fields)

    def legend(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('legendMode', mode)

    def measure_format(self, field: WizardFieldRef, *, format: Literal['number', 'percent'] | None = None, precision: int | None = None, unit: Literal['auto', 'k', 'm', 'b', 't'] | None = None, prefix: str | None = None, postfix: str | None = None, show_rank_delimiter: bool | None = None) -> Self:
        return self._measure_format(field, format=format, precision=precision, unit=unit, prefix=prefix, postfix=postfix, show_rank_delimiter=show_rank_delimiter)

    def navigator(self, *, mode: Literal['show', 'hide']) -> Self:
        return self._navigator(mode=mode)

    def nulls_mode(self, slot_name: Literal['y', 'y2'], *, mode: Literal['as-0', 'connect', 'ignore', 'use-previous']) -> Self:
        return self._set_slot_setting(slot_name, 'nulls', mode)

    def palette(self, *, id: PaletteId) -> Self:
        return self._palette(id=id)

    def segments(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('segments', fields)

    def shape_by_dimension(self, field: WizardFieldRef, *, shapes_map: Mapping[str, ShapeStyle] | None = None) -> Self:
        return self._shape_by_dimension(field, shapes_map=shapes_map)

    def shape_by_measure_name(self, *, shapes_map: Mapping[WizardFieldRef, ShapeStyle] | None = None) -> Self:
        return self._shape_by_measure_name(shapes_map=shapes_map)

    def sort(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('sort', fields)

    def tooltip(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('tooltip', mode)

    def tooltip_sum(self, *, enabled: bool) -> Self:
        return self._set_chart_setting('tooltipSum', 'on' if enabled else 'off')

class MetricWizardChartCreate(_MetricWizardChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            visualization_type='metric',
            name=name,
            location=location,
            operations=operations,
        )

    def y(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('measures', fields)

    def add_aggregated_measure(self, field: WizardAggregatedMeasure) -> Self:
        return self._add_aggregated_measure(field)

    def add_date_filter(self, field: WizardFieldRef, *, start: str, end: str, inclusive_end: bool = True) -> Self:
        return self._add_date_filter(field, start=start, end=end, inclusive_end=inclusive_end)

    def add_filter(self, field: WizardFieldRef, *, operation: FilterOperation, values: Sequence[str] = ()) -> Self:
        return self._add_filter(field, operation=operation, values=values)

    def add_local_field(self, field: WizardLocalField) -> Self:
        return self._add_local_field(field)

    def add_relative_date_filter(self, field: WizardFieldRef, *, start_offset: str, end_offset: str) -> Self:
        return self._add_relative_date_filter(field, start_offset=start_offset, end_offset=end_offset)

    def description(self, text: str) -> Self:
        return self._set_description(text)

    def font_color(self, *, color: str) -> Self:
        return self._font_color(color=color)

    def font_size(self, *, size: Literal['xs', 's', 'm', 'l']) -> Self:
        return self._font_size(size=size)

    def measure_format(self, field: WizardFieldRef, *, format: Literal['number', 'percent'] | None = None, precision: int | None = None, unit: Literal['auto', 'k', 'm', 'b', 't'] | None = None, prefix: str | None = None, postfix: str | None = None, show_rank_delimiter: bool | None = None) -> Self:
        return self._measure_format(field, format=format, precision=precision, unit=unit, prefix=prefix, postfix=postfix, show_rank_delimiter=show_rank_delimiter)

    def measure_title_mode(self, *, mode: Literal['by-field', 'manual', 'hide']) -> Self:
        return self._measure_title_mode(mode=mode)

class PieWizardChartCreate(_BaseWizardChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            visualization_type='pie',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('dimensions', fields)

    def y(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('measures', fields)

    def add_aggregated_measure(self, field: WizardAggregatedMeasure) -> Self:
        return self._add_aggregated_measure(field)

    def add_date_filter(self, field: WizardFieldRef, *, start: str, end: str, inclusive_end: bool = True) -> Self:
        return self._add_date_filter(field, start=start, end=end, inclusive_end=inclusive_end)

    def add_filter(self, field: WizardFieldRef, *, operation: FilterOperation, values: Sequence[str] = ()) -> Self:
        return self._add_filter(field, operation=operation, values=values)

    def add_local_field(self, field: WizardLocalField) -> Self:
        return self._add_local_field(field)

    def add_relative_date_filter(self, field: WizardFieldRef, *, start_offset: str, end_offset: str) -> Self:
        return self._add_relative_date_filter(field, start_offset=start_offset, end_offset=end_offset)

    def add_sort(self, field: WizardFieldRef, *, direction: Literal['asc', 'desc'] = 'asc') -> Self:
        return self._add_sort(field, direction=direction)

    def chart_title(self, *, text: str = '', mode: Literal['show', 'hide'] = 'show') -> Self:
        return self._chart_title(text=text, mode=mode)

    def color_by_dimension(self, field: WizardFieldRef) -> Self:
        return self._color_by_dimension(field)

    def description(self, text: str) -> Self:
        return self._set_description(text)

    def label_mode(self, *, mode: Literal['absolute', 'percent']) -> Self:
        return self._label_mode(mode=mode)

    def labels(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('labels', fields)

    def legend(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('legendMode', mode)

    def measure_format(self, field: WizardFieldRef, *, format: Literal['number', 'percent'] | None = None, precision: int | None = None, unit: Literal['auto', 'k', 'm', 'b', 't'] | None = None, prefix: str | None = None, postfix: str | None = None, show_rank_delimiter: bool | None = None) -> Self:
        return self._measure_format(field, format=format, precision=precision, unit=unit, prefix=prefix, postfix=postfix, show_rank_delimiter=show_rank_delimiter)

    def palette(self, *, id: PaletteId) -> Self:
        return self._palette(id=id)

    def sort(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('sort', fields)

    def tooltip(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('tooltip', mode)

class PivotTableWizardChartCreate(_PivotWizardChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            visualization_type='pivotTable',
            name=name,
            location=location,
            operations=operations,
        )

    def columns(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('columns', fields)

    def measures(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('measures', fields)

    def rows(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('rows', fields)

    def add_aggregated_measure(self, field: WizardAggregatedMeasure) -> Self:
        return self._add_aggregated_measure(field)

    def add_date_filter(self, field: WizardFieldRef, *, start: str, end: str, inclusive_end: bool = True) -> Self:
        return self._add_date_filter(field, start=start, end=end, inclusive_end=inclusive_end)

    def add_filter(self, field: WizardFieldRef, *, operation: FilterOperation, values: Sequence[str] = ()) -> Self:
        return self._add_filter(field, operation=operation, values=values)

    def add_hierarchy(self, hierarchy: WizardHierarchy) -> Self:
        return self._add_hierarchy(hierarchy)

    def add_local_field(self, field: WizardLocalField) -> Self:
        return self._add_local_field(field)

    def add_relative_date_filter(self, field: WizardFieldRef, *, start_offset: str, end_offset: str) -> Self:
        return self._add_relative_date_filter(field, start_offset=start_offset, end_offset=end_offset)

    def add_sort(self, field: WizardFieldRef, *, direction: Literal['asc', 'desc'] = 'asc') -> Self:
        return self._add_sort(field, direction=direction)

    def chart_title(self, *, text: str = '', mode: Literal['show', 'hide'] = 'show') -> Self:
        return self._chart_title(text=text, mode=mode)

    def color_by_measure(self, field: WizardFieldRef, *, mode: Literal['2-point', '3-point'] | None = None, palette: GradientPaletteId | None = None, reversed: bool | None = None) -> Self:
        return self._color_by_measure(field, mode=mode, palette=palette, reversed=reversed)

    def column_background(self, field: WizardFieldRef, *, mode: Literal['2-point', '3-point'] = '3-point', palette: GradientPaletteId = 'red-orange-green', thresholds: tuple[float, ...] | None = None, reversed: bool = False) -> Self:
        return self._column_background(field, mode=mode, palette=palette, thresholds=thresholds, reversed=reversed)

    def column_bars(self, field: WizardFieldRef, *, enabled: bool = True, color_type: Literal['one-color', 'two-color', 'gradient'] = 'one-color', color: str | None = None, palette: DiscretePaletteId | None = None, color_index: int | None = None, color_positive: str | None = None, color_negative: str | None = None, positive_color_index: int | None = None, negative_color_index: int | None = None, gradient_palette: GradientPaletteId | None = None, gradient_type: Literal['2-point', '3-point'] = '2-point', reversed: bool = False, show_labels: bool = True, show_in_totals: bool = False, align: Literal['default', 'left', 'right'] = 'default') -> Self:
        return self._column_bars(field, enabled=enabled, color_type=color_type, color=color, palette=palette, color_index=color_index, color_positive=color_positive, color_negative=color_negative, positive_color_index=positive_color_index, negative_color_index=negative_color_index, gradient_palette=gradient_palette, gradient_type=gradient_type, reversed=reversed, show_labels=show_labels, show_in_totals=show_in_totals, align=align)

    def column_title(self, field: WizardFieldRef, *, title: str) -> Self:
        return self._column_title(field, title=title)

    def description(self, text: str) -> Self:
        return self._set_description(text)

    def freeze_columns(self, *, count: int = 1) -> Self:
        return self._freeze_columns(count=count)

    def measure_format(self, field: WizardFieldRef, *, format: Literal['number', 'percent'] | None = None, precision: int | None = None, unit: Literal['auto', 'k', 'm', 'b', 't'] | None = None, prefix: str | None = None, postfix: str | None = None, show_rank_delimiter: bool | None = None) -> Self:
        return self._measure_format(field, format=format, precision=precision, unit=unit, prefix=prefix, postfix=postfix, show_rank_delimiter=show_rank_delimiter)

    def pagination(self, *, enabled: bool, limit: int = 100) -> Self:
        return self._pagination(enabled=enabled, limit=limit)

    def palette(self, *, id: PaletteId) -> Self:
        return self._palette(id=id)

    def sort(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('sort', fields)

    def subtotals(self, field: WizardFieldRef, *, enabled: bool) -> Self:
        return self._subtotals(field, enabled=enabled)

    def table_size(self, *, size: Literal['s', 'm', 'l']) -> Self:
        return self._table_size(size=size)

class ScatterWizardChartCreate(_ScatterWizardChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            visualization_type='scatter',
            name=name,
            location=location,
            operations=operations,
        )

    def points(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('points', fields)

    def size(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('size', fields)

    def x(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('x', fields)

    def y(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('y', fields)

    def add_aggregated_measure(self, field: WizardAggregatedMeasure) -> Self:
        return self._add_aggregated_measure(field)

    def add_date_filter(self, field: WizardFieldRef, *, start: str, end: str, inclusive_end: bool = True) -> Self:
        return self._add_date_filter(field, start=start, end=end, inclusive_end=inclusive_end)

    def add_filter(self, field: WizardFieldRef, *, operation: FilterOperation, values: Sequence[str] = ()) -> Self:
        return self._add_filter(field, operation=operation, values=values)

    def add_hierarchy(self, hierarchy: WizardHierarchy) -> Self:
        return self._add_hierarchy(hierarchy)

    def add_local_field(self, field: WizardLocalField) -> Self:
        return self._add_local_field(field)

    def add_relative_date_filter(self, field: WizardFieldRef, *, start_offset: str, end_offset: str) -> Self:
        return self._add_relative_date_filter(field, start_offset=start_offset, end_offset=end_offset)

    def add_sort(self, field: WizardFieldRef, *, direction: Literal['asc', 'desc'] = 'asc') -> Self:
        return self._add_sort(field, direction=direction)

    def axis_scale(self, slot_name: Literal['x', 'y'], *, scale: Literal['linear', 'logarithmic'] = 'linear', mode: Literal['auto', 'manual'] = 'auto', min: str | None = None, max: str | None = None) -> Self:
        return self._axis_scale(slot_name, scale=scale, mode=mode, min=min, max=max)

    def axis_title(self, slot_name: Literal['x', 'y'], *, mode: Literal['off', 'manual', 'auto'], text: str = '') -> Self:
        return self._axis_title(slot_name, mode=mode, text=text)

    def axis_visibility(self, slot_name: Literal['x', 'y'], *, mode: Literal['hide', 'show']) -> Self:
        return self._set_slot_setting(slot_name, 'axisVisibility', mode)

    def chart_title(self, *, text: str = '', mode: Literal['show', 'hide'] = 'show') -> Self:
        return self._chart_title(text=text, mode=mode)

    def color_by_dimension(self, field: WizardFieldRef) -> Self:
        return self._color_by_dimension(field)

    def color_by_measure(self, field: WizardFieldRef, *, mode: Literal['2-point', '3-point'] | None = None, palette: GradientPaletteId | None = None, reversed: bool | None = None) -> Self:
        return self._color_by_measure(field, mode=mode, palette=palette, reversed=reversed)

    def description(self, text: str) -> Self:
        return self._set_description(text)

    def grid(self, slot_name: Literal['x', 'y'], *, enabled: bool, step: int | None = None) -> Self:
        return self._grid(slot_name, enabled=enabled, step=step)

    def hide_labels(self, slot_name: Literal['x', 'y'], *, enabled: bool) -> Self:
        return self._set_slot_setting(slot_name, 'hideLabels', 'yes' if enabled else 'no')

    def legend(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('legendMode', mode)

    def measure_format(self, field: WizardFieldRef, *, format: Literal['number', 'percent'] | None = None, precision: int | None = None, unit: Literal['auto', 'k', 'm', 'b', 't'] | None = None, prefix: str | None = None, postfix: str | None = None, show_rank_delimiter: bool | None = None) -> Self:
        return self._measure_format(field, format=format, precision=precision, unit=unit, prefix=prefix, postfix=postfix, show_rank_delimiter=show_rank_delimiter)

    def palette(self, *, id: PaletteId) -> Self:
        return self._palette(id=id)

    def point_size_range(self, *, min_radius: float = 4.5, max_radius: float = 9.0) -> Self:
        return self._point_size_range(min_radius=min_radius, max_radius=max_radius)

    def shape_by_dimension(self, field: WizardFieldRef, *, shapes_map: Mapping[str, ShapeStyle] | None = None) -> Self:
        return self._shape_by_dimension(field, shapes_map=shapes_map)

    def sort(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('sort', fields)

    def tooltip(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('tooltip', mode)

class TreemapWizardChartCreate(_BaseWizardChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            visualization_type='treemap',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('dimensions', fields)

    def y(self, fields: Sequence[WizardFieldRef]) -> Self:
        return self._set_slot('measures', fields)

    def add_aggregated_measure(self, field: WizardAggregatedMeasure) -> Self:
        return self._add_aggregated_measure(field)

    def add_date_filter(self, field: WizardFieldRef, *, start: str, end: str, inclusive_end: bool = True) -> Self:
        return self._add_date_filter(field, start=start, end=end, inclusive_end=inclusive_end)

    def add_filter(self, field: WizardFieldRef, *, operation: FilterOperation, values: Sequence[str] = ()) -> Self:
        return self._add_filter(field, operation=operation, values=values)

    def add_local_field(self, field: WizardLocalField) -> Self:
        return self._add_local_field(field)

    def add_relative_date_filter(self, field: WizardFieldRef, *, start_offset: str, end_offset: str) -> Self:
        return self._add_relative_date_filter(field, start_offset=start_offset, end_offset=end_offset)

    def chart_title(self, *, text: str = '', mode: Literal['show', 'hide'] = 'show') -> Self:
        return self._chart_title(text=text, mode=mode)

    def color_by_dimension(self, field: WizardFieldRef) -> Self:
        return self._color_by_dimension(field)

    def color_by_measure(self, field: WizardFieldRef, *, mode: Literal['2-point', '3-point'] | None = None, palette: GradientPaletteId | None = None, reversed: bool | None = None) -> Self:
        return self._color_by_measure(field, mode=mode, palette=palette, reversed=reversed)

    def description(self, text: str) -> Self:
        return self._set_description(text)

    def measure_format(self, field: WizardFieldRef, *, format: Literal['number', 'percent'] | None = None, precision: int | None = None, unit: Literal['auto', 'k', 'm', 'b', 't'] | None = None, prefix: str | None = None, postfix: str | None = None, show_rank_delimiter: bool | None = None) -> Self:
        return self._measure_format(field, format=format, precision=precision, unit=unit, prefix=prefix, postfix=postfix, show_rank_delimiter=show_rank_delimiter)

    def palette(self, *, id: PaletteId) -> Self:
        return self._palette(id=id)

    def tooltip(self, *, mode: Literal['hide', 'show']) -> Self:
        return self._set_chart_setting('tooltip', mode)

class WizardChartCreateFactory:
    def __init__(self, operations: ChartOperations) -> None:
        self._operations = operations

    def area(self, *, name: str, location: EntryLocation) -> AreaWizardChartCreate:
        return AreaWizardChartCreate(name=name, location=location, operations=self._operations)

    def area_100p(self, *, name: str, location: EntryLocation) -> Area100pWizardChartCreate:
        return Area100pWizardChartCreate(name=name, location=location, operations=self._operations)

    def bar(self, *, name: str, location: EntryLocation) -> BarWizardChartCreate:
        return BarWizardChartCreate(name=name, location=location, operations=self._operations)

    def bar_100p(self, *, name: str, location: EntryLocation) -> Bar100pWizardChartCreate:
        return Bar100pWizardChartCreate(name=name, location=location, operations=self._operations)

    def column(self, *, name: str, location: EntryLocation) -> ColumnWizardChartCreate:
        return ColumnWizardChartCreate(name=name, location=location, operations=self._operations)

    def column_100p(self, *, name: str, location: EntryLocation) -> Column100pWizardChartCreate:
        return Column100pWizardChartCreate(name=name, location=location, operations=self._operations)

    def combined_chart(self, *, name: str, location: EntryLocation) -> CombinedChartWizardChartCreate:
        return CombinedChartWizardChartCreate(name=name, location=location, operations=self._operations)

    def donut(self, *, name: str, location: EntryLocation) -> DonutWizardChartCreate:
        return DonutWizardChartCreate(name=name, location=location, operations=self._operations)

    def flat_table(self, *, name: str, location: EntryLocation) -> FlatTableWizardChartCreate:
        return FlatTableWizardChartCreate(name=name, location=location, operations=self._operations)

    def funnel(self, *, name: str, location: EntryLocation) -> FunnelWizardChartCreate:
        return FunnelWizardChartCreate(name=name, location=location, operations=self._operations)

    def geolayer(self, *, name: str, location: EntryLocation) -> GeolayerWizardChartCreate:
        return GeolayerWizardChartCreate(name=name, location=location, operations=self._operations)

    def line(self, *, name: str, location: EntryLocation) -> LineWizardChartCreate:
        return LineWizardChartCreate(name=name, location=location, operations=self._operations)

    def indicator(self, *, name: str, location: EntryLocation) -> MetricWizardChartCreate:
        return MetricWizardChartCreate(name=name, location=location, operations=self._operations)

    def pie(self, *, name: str, location: EntryLocation) -> PieWizardChartCreate:
        return PieWizardChartCreate(name=name, location=location, operations=self._operations)

    def pivot_table(self, *, name: str, location: EntryLocation) -> PivotTableWizardChartCreate:
        return PivotTableWizardChartCreate(name=name, location=location, operations=self._operations)

    def scatter(self, *, name: str, location: EntryLocation) -> ScatterWizardChartCreate:
        return ScatterWizardChartCreate(name=name, location=location, operations=self._operations)

    def treemap(self, *, name: str, location: EntryLocation) -> TreemapWizardChartCreate:
        return TreemapWizardChartCreate(name=name, location=location, operations=self._operations)

class AdvancedChartNodeNodeCreate(_BaseEditorNodeCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            wire_type='advanced-chart_node',
            name=name,
            location=location,
            operations=operations,
        )

    def controls(self, value: str) -> Self:
        return self._set_tab('controls', value)

    def meta(self, value: str) -> Self:
        return self._set_tab('meta', value)

    def params(self, value: str) -> Self:
        return self._set_tab('params', value)

    def prepare(self, value: str) -> Self:
        return self._set_tab('prepare', value)

    def sources(self, value: str) -> Self:
        return self._set_tab('sources', value)

class ControlNodeNodeCreate(_BaseEditorNodeCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            wire_type='control_node',
            name=name,
            location=location,
            operations=operations,
        )

    def controls(self, value: str) -> Self:
        return self._set_tab('controls', value)

    def meta(self, value: str) -> Self:
        return self._set_tab('meta', value)

    def params(self, value: str) -> Self:
        return self._set_tab('params', value)

    def sources(self, value: str) -> Self:
        return self._set_tab('sources', value)

class D3NodeNodeCreate(_BaseEditorNodeCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            wire_type='d3_node',
            name=name,
            location=location,
            operations=operations,
        )

    def config(self, value: str) -> Self:
        return self._set_tab('config', value)

    def controls(self, value: str) -> Self:
        return self._set_tab('controls', value)

    def meta(self, value: str) -> Self:
        return self._set_tab('meta', value)

    def params(self, value: str) -> Self:
        return self._set_tab('params', value)

    def prepare(self, value: str) -> Self:
        return self._set_tab('prepare', value)

    def sources(self, value: str) -> Self:
        return self._set_tab('sources', value)

class MarkdownNodeNodeCreate(_BaseEditorNodeCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            wire_type='markdown_node',
            name=name,
            location=location,
            operations=operations,
        )

    def controls(self, value: str) -> Self:
        return self._set_tab('controls', value)

    def meta(self, value: str) -> Self:
        return self._set_tab('meta', value)

    def params(self, value: str) -> Self:
        return self._set_tab('params', value)

    def prepare(self, value: str) -> Self:
        return self._set_tab('prepare', value)

    def sources(self, value: str) -> Self:
        return self._set_tab('sources', value)

class TableNodeNodeCreate(_BaseEditorNodeCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            wire_type='table_node',
            name=name,
            location=location,
            operations=operations,
        )

    def config(self, value: str) -> Self:
        return self._set_tab('config', value)

    def controls(self, value: str) -> Self:
        return self._set_tab('controls', value)

    def meta(self, value: str) -> Self:
        return self._set_tab('meta', value)

    def params(self, value: str) -> Self:
        return self._set_tab('params', value)

    def prepare(self, value: str) -> Self:
        return self._set_tab('prepare', value)

    def sources(self, value: str) -> Self:
        return self._set_tab('sources', value)

class EnterpriseEditorChartCreateFactory:
    def __init__(self, operations: ChartOperations) -> None:
        self._operations = operations

    def advanced_chart(self, *, name: str, location: EntryLocation) -> AdvancedChartNodeNodeCreate:
        return AdvancedChartNodeNodeCreate(name=name, location=location, operations=self._operations)

    def selector(self, *, name: str, location: EntryLocation) -> ControlNodeNodeCreate:
        return ControlNodeNodeCreate(name=name, location=location, operations=self._operations)

    def gravity_charts(self, *, name: str, location: EntryLocation) -> D3NodeNodeCreate:
        return D3NodeNodeCreate(name=name, location=location, operations=self._operations)

    def markdown(self, *, name: str, location: EntryLocation) -> MarkdownNodeNodeCreate:
        return MarkdownNodeNodeCreate(name=name, location=location, operations=self._operations)

    def table(self, *, name: str, location: EntryLocation) -> TableNodeNodeCreate:
        return TableNodeNodeCreate(name=name, location=location, operations=self._operations)

class YacloudEditorChartCreateFactory:
    def __init__(self, operations: ChartOperations) -> None:
        self._operations = operations

    def advanced_chart(self, *, name: str, location: EntryLocation) -> AdvancedChartNodeNodeCreate:
        return AdvancedChartNodeNodeCreate(name=name, location=location, operations=self._operations)

    def selector(self, *, name: str, location: EntryLocation) -> ControlNodeNodeCreate:
        return ControlNodeNodeCreate(name=name, location=location, operations=self._operations)

    def gravity_charts(self, *, name: str, location: EntryLocation) -> D3NodeNodeCreate:
        return D3NodeNodeCreate(name=name, location=location, operations=self._operations)

    def markdown(self, *, name: str, location: EntryLocation) -> MarkdownNodeNodeCreate:
        return MarkdownNodeNodeCreate(name=name, location=location, operations=self._operations)

    def table(self, *, name: str, location: EntryLocation) -> TableNodeNodeCreate:
        return TableNodeNodeCreate(name=name, location=location, operations=self._operations)

class QlAreaChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='area',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('x', columns)

    def y(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('y', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('colors', columns)

    def labels(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('labels', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlArea100pChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='area100p',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('x', columns)

    def y(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('y', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('colors', columns)

    def labels(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('labels', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlBarChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='bar',
            name=name,
            location=location,
            operations=operations,
        )

    def y(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('y', columns)

    def x(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('x', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('colors', columns)

    def labels(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('labels', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlBar100pChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='bar100p',
            name=name,
            location=location,
            operations=operations,
        )

    def y(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('y', columns)

    def x(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('x', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('colors', columns)

    def labels(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('labels', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlColumnChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='column',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('x', columns)

    def y(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('y', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('colors', columns)

    def labels(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('labels', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlColumn100pChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='column100p',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('x', columns)

    def y(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('y', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('colors', columns)

    def labels(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('labels', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlDonutChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='donut',
            name=name,
            location=location,
            operations=operations,
        )

    def dimensions(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('dimensions', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('colors', columns)

    def measures(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('measures', columns)

    def labels(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('labels', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlFlatTableChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='flatTable',
            name=name,
            location=location,
            operations=operations,
        )

    def flat_table_columns(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('flat_table_columns', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('colors', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlLineChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='line',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('x', columns)

    def y(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('y', columns)

    def y2(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('y2', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('colors', columns)

    def labels(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('labels', columns)

    def shapes(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('shapes', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlMetricChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='metric',
            name=name,
            location=location,
            operations=operations,
        )

    def measures(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('measures', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('colors', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlPieChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='pie',
            name=name,
            location=location,
            operations=operations,
        )

    def dimensions(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('dimensions', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('colors', columns)

    def measures(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('measures', columns)

    def labels(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('labels', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlScatterChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='scatter',
            name=name,
            location=location,
            operations=operations,
        )

    def x(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('x', columns)

    def y(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('y', columns)

    def points(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('points', columns)

    def size(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('size', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('colors', columns)

    def shapes(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('shapes', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QlTreemapChartCreate(_BaseQLChartCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ChartOperations | None = None) -> None:
        super().__init__(
            viz_id='treemap',
            name=name,
            location=location,
            operations=operations,
        )

    def dimensions(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('dimensions', columns)

    def measures(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_placeholder('measures', columns)

    def colors(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('colors', columns)

    def tooltips(self, columns: Sequence[QLColumn | str]) -> Self:
        return self._set_data_section('tooltips', columns)

class QLChartCreateFactory:
    def __init__(self, operations: ChartOperations) -> None:
        self._operations = operations

    def area(self, *, name: str, location: EntryLocation) -> QlAreaChartCreate:
        return QlAreaChartCreate(name=name, location=location, operations=self._operations)

    def area_100p(self, *, name: str, location: EntryLocation) -> QlArea100pChartCreate:
        return QlArea100pChartCreate(name=name, location=location, operations=self._operations)

    def bar(self, *, name: str, location: EntryLocation) -> QlBarChartCreate:
        return QlBarChartCreate(name=name, location=location, operations=self._operations)

    def bar_100p(self, *, name: str, location: EntryLocation) -> QlBar100pChartCreate:
        return QlBar100pChartCreate(name=name, location=location, operations=self._operations)

    def column(self, *, name: str, location: EntryLocation) -> QlColumnChartCreate:
        return QlColumnChartCreate(name=name, location=location, operations=self._operations)

    def column_100p(self, *, name: str, location: EntryLocation) -> QlColumn100pChartCreate:
        return QlColumn100pChartCreate(name=name, location=location, operations=self._operations)

    def donut(self, *, name: str, location: EntryLocation) -> QlDonutChartCreate:
        return QlDonutChartCreate(name=name, location=location, operations=self._operations)

    def flat_table(self, *, name: str, location: EntryLocation) -> QlFlatTableChartCreate:
        return QlFlatTableChartCreate(name=name, location=location, operations=self._operations)

    def line(self, *, name: str, location: EntryLocation) -> QlLineChartCreate:
        return QlLineChartCreate(name=name, location=location, operations=self._operations)

    def indicator(self, *, name: str, location: EntryLocation) -> QlMetricChartCreate:
        return QlMetricChartCreate(name=name, location=location, operations=self._operations)

    def pie(self, *, name: str, location: EntryLocation) -> QlPieChartCreate:
        return QlPieChartCreate(name=name, location=location, operations=self._operations)

    def scatter(self, *, name: str, location: EntryLocation) -> QlScatterChartCreate:
        return QlScatterChartCreate(name=name, location=location, operations=self._operations)

    def treemap(self, *, name: str, location: EntryLocation) -> QlTreemapChartCreate:
        return QlTreemapChartCreate(name=name, location=location, operations=self._operations)
