# AUTOGENERATED by scripts/generate_sdk.py. Do not edit by hand.
# ruff: noqa
from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Literal

from typing_extensions import Self

from datalens_sdk.domain.entry_location import EntryLocation
from datalens_sdk.domain.ports import ConnectionOperations
from datalens_sdk.runtime import BaseConnectionCreate, ConnectorMetadata

INSTALLATION = 'enterprise'
METADATA: dict[str, ConnectorMetadata] = {
    'appmetrica_api': ConnectorMetadata(
        connector='appmetrica_api',
        required=frozenset(['counter_id', 'token']),
        available_fields=frozenset(['accuracy', 'collection_id', 'counter_id', 'data_export_forbidden', 'description', 'dir_path', 'name', 'token', 'type', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': ''},
        enum_restrictions={},
    ),
    'chyt': ConnectorMetadata(
        connector='chyt',
        required=frozenset(['alias', 'host', 'port', 'token']),
        available_fields=frozenset(['alias', 'cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'description', 'dir_path', 'host', 'name', 'port', 'raw_sql_level', 'secure', 'token', 'type', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': '', 'raw_sql_level': 'off'},
        enum_restrictions={'raw_sql_level': ['off', 'subselect', 'template', 'dashsql']},
    ),
    'clickhouse': ConnectorMetadata(
        connector='clickhouse',
        required=frozenset(['host', 'port']),
        available_fields=frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'connection_manager_cloud_id', 'connection_manager_connection_id', 'connection_manager_delegation_is_set', 'connection_manager_folder_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'experimental_features', 'host', 'mdb_cluster_id', 'mdb_folder_id', 'name', 'password', 'port', 'raw_sql_level', 'readonly', 'secure', 'ssl_ca', 'ssl_ca_verify', 'type', 'username', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': '', 'experimental_features': 'off', 'raw_sql_level': 'off', 'readonly': 2, 'ssl_ca_verify': 'on'},
        enum_restrictions={'raw_sql_level': ['off', 'subselect', 'template', 'dashsql'], 'secure': ['on', 'off']},
    ),
    'greenplum': ConnectorMetadata(
        connector='greenplum',
        required=frozenset(['host', 'password', 'port', 'username']),
        available_fields=frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'enforce_collate', 'host', 'mdb_cluster_id', 'mdb_folder_id', 'name', 'password', 'port', 'raw_sql_level', 'ssl_ca', 'ssl_enable', 'type', 'username', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': '', 'enforce_collate': 'auto', 'raw_sql_level': 'off', 'ssl_enable': 'off'},
        enum_restrictions={'enforce_collate': ['auto', 'on', 'off'], 'raw_sql_level': ['off', 'subselect', 'template', 'dashsql']},
    ),
    'json_api': ConnectorMetadata(
        connector='json_api',
        required=frozenset(['allowed_methods', 'host', 'port']),
        available_fields=frozenset(['allowed_methods', 'collection_id', 'description', 'dir_path', 'host', 'name', 'path', 'plain_headers', 'port', 'secret_headers', 'secure', 'type', 'workbook_id']),
        defaults={'description': ''},
        enum_restrictions={},
    ),
    'metrika_api': ConnectorMetadata(
        connector='metrika_api',
        required=frozenset(['counter_id', 'token']),
        available_fields=frozenset(['accuracy', 'collection_id', 'counter_id', 'data_export_forbidden', 'description', 'dir_path', 'name', 'token', 'type', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': ''},
        enum_restrictions={},
    ),
    'mssql': ConnectorMetadata(
        connector='mssql',
        required=frozenset(['host', 'password', 'port', 'username']),
        available_fields=frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'host', 'name', 'password', 'port', 'raw_sql_level', 'type', 'username', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': '', 'raw_sql_level': 'off'},
        enum_restrictions={'raw_sql_level': ['off', 'subselect', 'template', 'dashsql']},
    ),
    'mysql': ConnectorMetadata(
        connector='mysql',
        required=frozenset(['host', 'port']),
        available_fields=frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'connection_manager_cloud_id', 'connection_manager_connection_id', 'connection_manager_delegation_is_set', 'connection_manager_folder_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'enforce_collate', 'host', 'mdb_cluster_id', 'mdb_folder_id', 'name', 'password', 'port', 'raw_sql_level', 'ssl_ca', 'ssl_enable', 'type', 'username', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': '', 'enforce_collate': 'off', 'raw_sql_level': 'off', 'ssl_enable': 'off'},
        enum_restrictions={'enforce_collate': ['auto', 'on', 'off'], 'raw_sql_level': ['off', 'subselect', 'template', 'dashsql']},
    ),
    'oracle': ConnectorMetadata(
        connector='oracle',
        required=frozenset(['db_connect_method', 'host', 'password', 'port', 'username']),
        available_fields=frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'db_connect_method', 'db_name', 'description', 'dir_path', 'host', 'name', 'password', 'port', 'raw_sql_level', 'ssl_ca', 'ssl_enable', 'type', 'username', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': '', 'raw_sql_level': 'off', 'ssl_enable': 'off'},
        enum_restrictions={'db_connect_method': ['sid', 'service_name'], 'raw_sql_level': ['off', 'subselect', 'template', 'dashsql']},
    ),
    'postgres': ConnectorMetadata(
        connector='postgres',
        required=frozenset(['host', 'port']),
        available_fields=frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'connection_manager_cloud_id', 'connection_manager_connection_id', 'connection_manager_delegation_is_set', 'connection_manager_folder_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'enforce_collate', 'host', 'mdb_cluster_id', 'mdb_folder_id', 'name', 'password', 'port', 'raw_sql_level', 'ssl_ca', 'ssl_enable', 'type', 'username', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': '', 'enforce_collate': 'auto', 'raw_sql_level': 'off', 'ssl_enable': 'off'},
        enum_restrictions={'enforce_collate': ['auto', 'on', 'off'], 'raw_sql_level': ['off', 'subselect', 'template', 'dashsql']},
    ),
    'promql': ConnectorMetadata(
        connector='promql',
        required=frozenset(['host', 'port']),
        available_fields=frozenset(['auth_header', 'auth_type', 'cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'host', 'name', 'password', 'path', 'port', 'secure', 'type', 'username', 'workbook_id']),
        defaults={'auth_type': 'password', 'data_export_forbidden': 'off', 'description': ''},
        enum_restrictions={},
    ),
    'trino': ConnectorMetadata(
        connector='trino',
        required=frozenset(['host', 'listing_sources']),
        available_fields=frozenset(['auth_type', 'cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'cloud_id', 'collection_id', 'data_export_forbidden', 'db_name', 'delegation_is_set', 'description', 'dir_path', 'folder_id', 'host', 'jwt', 'listing_sources', 'mdb_cluster_id', 'name', 'password', 'port', 'raw_sql_level', 'service_account_id', 'ssl_ca', 'ssl_enable', 'type', 'username', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': '', 'raw_sql_level': 'off', 'ssl_enable': 'off'},
        enum_restrictions={'raw_sql_level': ['off', 'subselect', 'template', 'dashsql']},
    ),
    'ydb': ConnectorMetadata(
        connector='ydb',
        required=frozenset(['cloud_id', 'db_name', 'folder_id', 'host', 'port', 'service_account_id']),
        available_fields=frozenset(['auth_type', 'cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'cloud_id', 'collection_id', 'data_export_forbidden', 'db_name', 'delegation_is_set', 'description', 'dir_path', 'folder_id', 'host', 'mdb_cluster_id', 'mdb_folder_id', 'name', 'port', 'raw_sql_level', 'service_account_id', 'ssl_ca', 'ssl_enable', 'token', 'type', 'username', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': '', 'raw_sql_level': 'off', 'ssl_enable': 'on'},
        enum_restrictions={'auth_type': ['anonymous', 'password', 'oauth'], 'raw_sql_level': ['off', 'subselect', 'template', 'dashsql']},
    ),
}

class AppmetricaApiConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='appmetrica_api',
            metadata=METADATA['appmetrica_api'],
            operations=operations,
        )

    def accuracy(self, value: float) -> Self:
        return self._set('accuracy', value)

    def counter_id(self, value: str) -> Self:
        return self._set('counter_id', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def token(self, value: str) -> Self:
        return self._set('token', value)

class ChytConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='chyt',
            metadata=METADATA['chyt'],
            operations=operations,
        )

    def alias(self, value: str) -> Self:
        return self._set('alias', value)

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def host(self, value: str) -> Self:
        return self._set('host', value)

    def port(self, value: int) -> Self:
        return self._set('port', value)

    def raw_sql_level(self, value: Literal['off', 'subselect', 'template', 'dashsql']) -> Self:
        return self._set('raw_sql_level', value)

    def secure(self, value: bool) -> Self:
        return self._set('secure', value)

    def token(self, value: str) -> Self:
        return self._set('token', value)

class ClickhouseConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='clickhouse',
            metadata=METADATA['clickhouse'],
            operations=operations,
        )

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def connection_manager_cloud_id(self, value: str) -> Self:
        return self._set('connection_manager_cloud_id', value)

    def connection_manager_connection_id(self, value: str) -> Self:
        return self._set('connection_manager_connection_id', value)

    def connection_manager_delegation_is_set(self, value: bool) -> Self:
        return self._set('connection_manager_delegation_is_set', value)

    def connection_manager_folder_id(self, value: str) -> Self:
        return self._set('connection_manager_folder_id', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def db_name(self, value: str) -> Self:
        return self._set('db_name', value)

    def experimental_features(self, value: str) -> Self:
        return self._set('experimental_features', value)

    def host(self, value: str) -> Self:
        return self._set('host', value)

    def mdb_cluster_id(self, value: str) -> Self:
        return self._set('mdb_cluster_id', value)

    def mdb_folder_id(self, value: str) -> Self:
        return self._set('mdb_folder_id', value)

    def password(self, value: str) -> Self:
        return self._set('password', value)

    def port(self, value: int) -> Self:
        return self._set('port', value)

    def raw_sql_level(self, value: Literal['off', 'subselect', 'template', 'dashsql']) -> Self:
        return self._set('raw_sql_level', value)

    def readonly(self, value: int) -> Self:
        return self._set('readonly', value)

    def secure(self, value: Literal['on', 'off']) -> Self:
        return self._set('secure', value)

    def ssl_ca(self, value: Mapping[str, object]) -> Self:
        return self._set('ssl_ca', value)

    def ssl_ca_verify(self, value: str) -> Self:
        return self._set('ssl_ca_verify', value)

    def username(self, value: str) -> Self:
        return self._set('username', value)

class GreenplumConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='greenplum',
            metadata=METADATA['greenplum'],
            operations=operations,
        )

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def db_name(self, value: str) -> Self:
        return self._set('db_name', value)

    def enforce_collate(self, value: Literal['auto', 'on', 'off']) -> Self:
        return self._set('enforce_collate', value)

    def host(self, value: str) -> Self:
        return self._set('host', value)

    def mdb_cluster_id(self, value: str) -> Self:
        return self._set('mdb_cluster_id', value)

    def mdb_folder_id(self, value: str) -> Self:
        return self._set('mdb_folder_id', value)

    def password(self, value: str) -> Self:
        return self._set('password', value)

    def port(self, value: int) -> Self:
        return self._set('port', value)

    def raw_sql_level(self, value: Literal['off', 'subselect', 'template', 'dashsql']) -> Self:
        return self._set('raw_sql_level', value)

    def ssl_ca(self, value: Mapping[str, object]) -> Self:
        return self._set('ssl_ca', value)

    def ssl_enable(self, value: str) -> Self:
        return self._set('ssl_enable', value)

    def username(self, value: str) -> Self:
        return self._set('username', value)

class JsonApiConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='json_api',
            metadata=METADATA['json_api'],
            operations=operations,
        )

    def allowed_methods(self, value: Sequence[object]) -> Self:
        return self._set('allowed_methods', value)

    def host(self, value: str) -> Self:
        return self._set('host', value)

    def path(self, value: str) -> Self:
        return self._set('path', value)

    def plain_headers(self, value: Mapping[str, object]) -> Self:
        return self._set('plain_headers', value)

    def port(self, value: int) -> Self:
        return self._set('port', value)

    def secret_headers(self, value: Mapping[str, object]) -> Self:
        return self._set('secret_headers', value)

    def secure(self, value: bool) -> Self:
        return self._set('secure', value)

class MetrikaApiConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='metrika_api',
            metadata=METADATA['metrika_api'],
            operations=operations,
        )

    def accuracy(self, value: float) -> Self:
        return self._set('accuracy', value)

    def counter_id(self, value: str) -> Self:
        return self._set('counter_id', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def token(self, value: str) -> Self:
        return self._set('token', value)

class MssqlConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='mssql',
            metadata=METADATA['mssql'],
            operations=operations,
        )

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def db_name(self, value: str) -> Self:
        return self._set('db_name', value)

    def host(self, value: str) -> Self:
        return self._set('host', value)

    def password(self, value: str) -> Self:
        return self._set('password', value)

    def port(self, value: int) -> Self:
        return self._set('port', value)

    def raw_sql_level(self, value: Literal['off', 'subselect', 'template', 'dashsql']) -> Self:
        return self._set('raw_sql_level', value)

    def username(self, value: str) -> Self:
        return self._set('username', value)

class MysqlConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='mysql',
            metadata=METADATA['mysql'],
            operations=operations,
        )

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def connection_manager_cloud_id(self, value: str) -> Self:
        return self._set('connection_manager_cloud_id', value)

    def connection_manager_connection_id(self, value: str) -> Self:
        return self._set('connection_manager_connection_id', value)

    def connection_manager_delegation_is_set(self, value: bool) -> Self:
        return self._set('connection_manager_delegation_is_set', value)

    def connection_manager_folder_id(self, value: str) -> Self:
        return self._set('connection_manager_folder_id', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def db_name(self, value: str) -> Self:
        return self._set('db_name', value)

    def enforce_collate(self, value: Literal['auto', 'on', 'off']) -> Self:
        return self._set('enforce_collate', value)

    def host(self, value: str) -> Self:
        return self._set('host', value)

    def mdb_cluster_id(self, value: str) -> Self:
        return self._set('mdb_cluster_id', value)

    def mdb_folder_id(self, value: str) -> Self:
        return self._set('mdb_folder_id', value)

    def password(self, value: str) -> Self:
        return self._set('password', value)

    def port(self, value: int) -> Self:
        return self._set('port', value)

    def raw_sql_level(self, value: Literal['off', 'subselect', 'template', 'dashsql']) -> Self:
        return self._set('raw_sql_level', value)

    def ssl_ca(self, value: Mapping[str, object]) -> Self:
        return self._set('ssl_ca', value)

    def ssl_enable(self, value: str) -> Self:
        return self._set('ssl_enable', value)

    def username(self, value: str) -> Self:
        return self._set('username', value)

class OracleConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='oracle',
            metadata=METADATA['oracle'],
            operations=operations,
        )

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def db_connect_method(self, value: Literal['sid', 'service_name']) -> Self:
        return self._set('db_connect_method', value)

    def db_name(self, value: str) -> Self:
        return self._set('db_name', value)

    def host(self, value: str) -> Self:
        return self._set('host', value)

    def password(self, value: str) -> Self:
        return self._set('password', value)

    def port(self, value: int) -> Self:
        return self._set('port', value)

    def raw_sql_level(self, value: Literal['off', 'subselect', 'template', 'dashsql']) -> Self:
        return self._set('raw_sql_level', value)

    def ssl_ca(self, value: Mapping[str, object]) -> Self:
        return self._set('ssl_ca', value)

    def ssl_enable(self, value: str) -> Self:
        return self._set('ssl_enable', value)

    def username(self, value: str) -> Self:
        return self._set('username', value)

class PostgresConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='postgres',
            metadata=METADATA['postgres'],
            operations=operations,
        )

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def connection_manager_cloud_id(self, value: str) -> Self:
        return self._set('connection_manager_cloud_id', value)

    def connection_manager_connection_id(self, value: str) -> Self:
        return self._set('connection_manager_connection_id', value)

    def connection_manager_delegation_is_set(self, value: bool) -> Self:
        return self._set('connection_manager_delegation_is_set', value)

    def connection_manager_folder_id(self, value: str) -> Self:
        return self._set('connection_manager_folder_id', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def db_name(self, value: str) -> Self:
        return self._set('db_name', value)

    def enforce_collate(self, value: Literal['auto', 'on', 'off']) -> Self:
        return self._set('enforce_collate', value)

    def host(self, value: str) -> Self:
        return self._set('host', value)

    def mdb_cluster_id(self, value: str) -> Self:
        return self._set('mdb_cluster_id', value)

    def mdb_folder_id(self, value: str) -> Self:
        return self._set('mdb_folder_id', value)

    def password(self, value: str) -> Self:
        return self._set('password', value)

    def port(self, value: int) -> Self:
        return self._set('port', value)

    def raw_sql_level(self, value: Literal['off', 'subselect', 'template', 'dashsql']) -> Self:
        return self._set('raw_sql_level', value)

    def ssl_ca(self, value: Mapping[str, object]) -> Self:
        return self._set('ssl_ca', value)

    def ssl_enable(self, value: str) -> Self:
        return self._set('ssl_enable', value)

    def username(self, value: str) -> Self:
        return self._set('username', value)

class PromqlConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='promql',
            metadata=METADATA['promql'],
            operations=operations,
        )

    def auth_header(self, value: str) -> Self:
        return self._set('auth_header', value)

    def auth_type(self, value: str) -> Self:
        return self._set('auth_type', value)

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def db_name(self, value: str) -> Self:
        return self._set('db_name', value)

    def host(self, value: str) -> Self:
        return self._set('host', value)

    def password(self, value: str) -> Self:
        return self._set('password', value)

    def path(self, value: str) -> Self:
        return self._set('path', value)

    def port(self, value: int) -> Self:
        return self._set('port', value)

    def secure(self, value: bool) -> Self:
        return self._set('secure', value)

    def username(self, value: str) -> Self:
        return self._set('username', value)

class TrinoConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='trino',
            metadata=METADATA['trino'],
            operations=operations,
        )

    def auth_type(self, value: Mapping[str, object]) -> Self:
        return self._set('auth_type', value)

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def cloud_id(self, value: str) -> Self:
        return self._set('cloud_id', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def db_name(self, value: str) -> Self:
        return self._set('db_name', value)

    def delegation_is_set(self, value: bool) -> Self:
        return self._set('delegation_is_set', value)

    def folder_id(self, value: str) -> Self:
        return self._set('folder_id', value)

    def host(self, value: str) -> Self:
        return self._set('host', value)

    def jwt(self, value: str) -> Self:
        return self._set('jwt', value)

    def listing_sources(self, value: Mapping[str, object]) -> Self:
        return self._set('listing_sources', value)

    def mdb_cluster_id(self, value: str) -> Self:
        return self._set('mdb_cluster_id', value)

    def password(self, value: str) -> Self:
        return self._set('password', value)

    def port(self, value: int) -> Self:
        return self._set('port', value)

    def raw_sql_level(self, value: Literal['off', 'subselect', 'template', 'dashsql']) -> Self:
        return self._set('raw_sql_level', value)

    def service_account_id(self, value: str) -> Self:
        return self._set('service_account_id', value)

    def ssl_ca(self, value: Mapping[str, object]) -> Self:
        return self._set('ssl_ca', value)

    def ssl_enable(self, value: str) -> Self:
        return self._set('ssl_enable', value)

    def username(self, value: str) -> Self:
        return self._set('username', value)

class YdbConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='ydb',
            metadata=METADATA['ydb'],
            operations=operations,
        )

    def auth_type(self, value: Literal['anonymous', 'password', 'oauth']) -> Self:
        return self._set('auth_type', value)

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def cloud_id(self, value: str) -> Self:
        return self._set('cloud_id', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def db_name(self, value: str) -> Self:
        return self._set('db_name', value)

    def delegation_is_set(self, value: bool) -> Self:
        return self._set('delegation_is_set', value)

    def folder_id(self, value: str) -> Self:
        return self._set('folder_id', value)

    def host(self, value: str) -> Self:
        return self._set('host', value)

    def mdb_cluster_id(self, value: str) -> Self:
        return self._set('mdb_cluster_id', value)

    def mdb_folder_id(self, value: str) -> Self:
        return self._set('mdb_folder_id', value)

    def port(self, value: int) -> Self:
        return self._set('port', value)

    def raw_sql_level(self, value: Literal['off', 'subselect', 'template', 'dashsql']) -> Self:
        return self._set('raw_sql_level', value)

    def service_account_id(self, value: str) -> Self:
        return self._set('service_account_id', value)

    def ssl_ca(self, value: Mapping[str, object]) -> Self:
        return self._set('ssl_ca', value)

    def ssl_enable(self, value: str) -> Self:
        return self._set('ssl_enable', value)

    def token(self, value: str) -> Self:
        return self._set('token', value)

    def username(self, value: str) -> Self:
        return self._set('username', value)

class ConnectionCreateFactory:
    def __init__(self, operations: ConnectionOperations) -> None:
        self._operations = operations

    def appmetrica_api(self, *, name: str, location: EntryLocation) -> AppmetricaApiConnectionCreate:
        return AppmetricaApiConnectionCreate(name=name, location=location, operations=self._operations)

    def chyt(self, *, name: str, location: EntryLocation) -> ChytConnectionCreate:
        return ChytConnectionCreate(name=name, location=location, operations=self._operations)

    def clickhouse(self, *, name: str, location: EntryLocation) -> ClickhouseConnectionCreate:
        return ClickhouseConnectionCreate(name=name, location=location, operations=self._operations)

    def greenplum(self, *, name: str, location: EntryLocation) -> GreenplumConnectionCreate:
        return GreenplumConnectionCreate(name=name, location=location, operations=self._operations)

    def json_api(self, *, name: str, location: EntryLocation) -> JsonApiConnectionCreate:
        return JsonApiConnectionCreate(name=name, location=location, operations=self._operations)

    def metrika_api(self, *, name: str, location: EntryLocation) -> MetrikaApiConnectionCreate:
        return MetrikaApiConnectionCreate(name=name, location=location, operations=self._operations)

    def mssql(self, *, name: str, location: EntryLocation) -> MssqlConnectionCreate:
        return MssqlConnectionCreate(name=name, location=location, operations=self._operations)

    def mysql(self, *, name: str, location: EntryLocation) -> MysqlConnectionCreate:
        return MysqlConnectionCreate(name=name, location=location, operations=self._operations)

    def oracle(self, *, name: str, location: EntryLocation) -> OracleConnectionCreate:
        return OracleConnectionCreate(name=name, location=location, operations=self._operations)

    def postgres(self, *, name: str, location: EntryLocation) -> PostgresConnectionCreate:
        return PostgresConnectionCreate(name=name, location=location, operations=self._operations)

    def promql(self, *, name: str, location: EntryLocation) -> PromqlConnectionCreate:
        return PromqlConnectionCreate(name=name, location=location, operations=self._operations)

    def trino(self, *, name: str, location: EntryLocation) -> TrinoConnectionCreate:
        return TrinoConnectionCreate(name=name, location=location, operations=self._operations)

    def ydb(self, *, name: str, location: EntryLocation) -> YdbConnectionCreate:
        return YdbConnectionCreate(name=name, location=location, operations=self._operations)
