# AUTOGENERATED by scripts/generate_sdk.py. Do not edit by hand.
# ruff: noqa
from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Literal

from typing_extensions import Self

from datalens_sdk.domain.entry_location import EntryLocation
from datalens_sdk.domain.ports import ConnectionOperations
from datalens_sdk.runtime import BaseConnectionCreate, ConnectorMetadata

INSTALLATION = 'yacloud'
METADATA: dict[str, ConnectorMetadata] = {
    'appmetrica_api': ConnectorMetadata(
        connector='appmetrica_api',
        required=frozenset(['counter_id', 'token']),
        available_fields=frozenset(['accuracy', 'collection_id', 'counter_id', 'data_export_forbidden', 'description', 'dir_path', 'name', 'token', 'type', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': ''},
        enum_restrictions={},
    ),
    'bigquery': ConnectorMetadata(
        connector='bigquery',
        required=frozenset(['credentials', 'project_id']),
        available_fields=frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'credentials', 'description', 'dir_path', 'name', 'project_id', 'raw_sql_level', 'type', 'workbook_id']),
        defaults={'description': '', 'raw_sql_level': 'off'},
        enum_restrictions={'raw_sql_level': ['off', 'subselect', 'template', 'dashsql']},
    ),
    'bitrix24': ConnectorMetadata(
        connector='bitrix24',
        required=frozenset(['portal', 'token']),
        available_fields=frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'description', 'dir_path', 'name', 'portal', 'token', 'type', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': ''},
        enum_restrictions={},
    ),
    'ch_billing_analytics': ConnectorMetadata(
        connector='ch_billing_analytics',
        required=frozenset([]),
        available_fields=frozenset(['collection_id', 'description', 'dir_path', 'name', 'type', 'workbook_id']),
        defaults={'description': ''},
        enum_restrictions={},
    ),
    'ch_ya_music_podcast_stats': ConnectorMetadata(
        connector='ch_ya_music_podcast_stats',
        required=frozenset(['token']),
        available_fields=frozenset(['collection_id', 'description', 'dir_path', 'name', 'token', 'type', 'workbook_id']),
        defaults={'description': ''},
        enum_restrictions={},
    ),
    'chyt': ConnectorMetadata(
        connector='chyt',
        required=frozenset(['alias', 'host', 'port', 'token']),
        available_fields=frozenset(['alias', 'cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'description', 'dir_path', 'host', 'name', 'port', 'raw_sql_level', 'secure', 'token', 'type', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': '', 'raw_sql_level': 'off'},
        enum_restrictions={'raw_sql_level': ['off', 'subselect', 'template', 'dashsql']},
    ),
    'clickhouse': ConnectorMetadata(
        connector='clickhouse',
        required=frozenset(['host', 'port']),
        available_fields=frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'connection_manager_cloud_id', 'connection_manager_connection_id', 'connection_manager_delegation_is_set', 'connection_manager_folder_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'experimental_features', 'host', 'mdb_cluster_id', 'mdb_folder_id', 'name', 'password', 'port', 'raw_sql_level', 'readonly', 'secure', 'ssl_ca', 'ssl_ca_verify', 'type', 'username', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': '', 'experimental_features': 'off', 'raw_sql_level': 'off', 'readonly': 2, 'ssl_ca_verify': 'on'},
        enum_restrictions={'raw_sql_level': ['off', 'subselect', 'template', 'dashsql']},
    ),
    'equeo': ConnectorMetadata(
        connector='equeo',
        required=frozenset(['access_token']),
        available_fields=frozenset(['access_token', 'collection_id', 'description', 'dir_path', 'name', 'type', 'workbook_id']),
        defaults={'description': ''},
        enum_restrictions={},
    ),
    'extractor1c': ConnectorMetadata(
        connector='extractor1c',
        required=frozenset(['access_token']),
        available_fields=frozenset(['access_token', 'collection_id', 'description', 'dir_path', 'name', 'type', 'workbook_id']),
        defaults={'description': ''},
        enum_restrictions={},
    ),
    'greenplum': ConnectorMetadata(
        connector='greenplum',
        required=frozenset(['host', 'password', 'port', 'username']),
        available_fields=frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'enforce_collate', 'host', 'mdb_cluster_id', 'mdb_folder_id', 'name', 'password', 'port', 'raw_sql_level', 'ssl_ca', 'ssl_enable', 'type', 'username', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': '', 'enforce_collate': 'auto', 'raw_sql_level': 'off', 'ssl_enable': 'off'},
        enum_restrictions={'enforce_collate': ['auto', 'on', 'off'], 'raw_sql_level': ['off', 'subselect', 'template', 'dashsql']},
    ),
    'gsheets': ConnectorMetadata(
        connector='gsheets',
        required=frozenset(['url']),
        available_fields=frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'description', 'dir_path', 'name', 'type', 'url', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': ''},
        enum_restrictions={},
    ),
    'json_api': ConnectorMetadata(
        connector='json_api',
        required=frozenset(['allowed_methods', 'host', 'port']),
        available_fields=frozenset(['allowed_methods', 'collection_id', 'description', 'dir_path', 'host', 'name', 'path', 'plain_headers', 'port', 'secret_headers', 'secure', 'type', 'workbook_id']),
        defaults={'description': ''},
        enum_restrictions={},
    ),
    'kontur_market': ConnectorMetadata(
        connector='kontur_market',
        required=frozenset(['access_token']),
        available_fields=frozenset(['access_token', 'collection_id', 'description', 'dir_path', 'name', 'type', 'workbook_id']),
        defaults={'description': ''},
        enum_restrictions={},
    ),
    'metrika_api': ConnectorMetadata(
        connector='metrika_api',
        required=frozenset(['counter_id', 'token']),
        available_fields=frozenset(['accuracy', 'collection_id', 'counter_id', 'data_export_forbidden', 'description', 'dir_path', 'name', 'token', 'type', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': ''},
        enum_restrictions={},
    ),
    'monitoring': ConnectorMetadata(
        connector='monitoring',
        required=frozenset(['cloud_id', 'folder_id', 'service_account_id']),
        available_fields=frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'cloud_id', 'collection_id', 'delegation_is_set', 'description', 'dir_path', 'folder_id', 'name', 'service_account_id', 'type', 'workbook_id']),
        defaults={'description': ''},
        enum_restrictions={},
    ),
    'moysklad': ConnectorMetadata(
        connector='moysklad',
        required=frozenset(['access_token']),
        available_fields=frozenset(['access_token', 'collection_id', 'description', 'dir_path', 'name', 'type', 'workbook_id']),
        defaults={'description': ''},
        enum_restrictions={},
    ),
    'mssql': ConnectorMetadata(
        connector='mssql',
        required=frozenset(['host', 'password', 'port', 'username']),
        available_fields=frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'host', 'name', 'password', 'port', 'raw_sql_level', 'type', 'username', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': '', 'raw_sql_level': 'off'},
        enum_restrictions={'raw_sql_level': ['off', 'subselect', 'template', 'dashsql']},
    ),
    'mysql': ConnectorMetadata(
        connector='mysql',
        required=frozenset(['host', 'port']),
        available_fields=frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'connection_manager_cloud_id', 'connection_manager_connection_id', 'connection_manager_delegation_is_set', 'connection_manager_folder_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'enforce_collate', 'host', 'mdb_cluster_id', 'mdb_folder_id', 'name', 'password', 'port', 'raw_sql_level', 'ssl_ca', 'ssl_enable', 'type', 'username', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': '', 'enforce_collate': 'off', 'raw_sql_level': 'off', 'ssl_enable': 'off'},
        enum_restrictions={'enforce_collate': ['auto', 'on', 'off'], 'raw_sql_level': ['off', 'subselect', 'template', 'dashsql']},
    ),
    'oracle': ConnectorMetadata(
        connector='oracle',
        required=frozenset(['db_connect_method', 'host', 'password', 'port', 'username']),
        available_fields=frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'db_connect_method', 'db_name', 'description', 'dir_path', 'host', 'name', 'password', 'port', 'raw_sql_level', 'ssl_ca', 'ssl_enable', 'type', 'username', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': '', 'raw_sql_level': 'off', 'ssl_enable': 'off'},
        enum_restrictions={'db_connect_method': ['sid', 'service_name'], 'raw_sql_level': ['off', 'subselect', 'template', 'dashsql']},
    ),
    'postgres': ConnectorMetadata(
        connector='postgres',
        required=frozenset(['host', 'port']),
        available_fields=frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'connection_manager_cloud_id', 'connection_manager_connection_id', 'connection_manager_delegation_is_set', 'connection_manager_folder_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'enforce_collate', 'host', 'mdb_cluster_id', 'mdb_folder_id', 'name', 'password', 'port', 'raw_sql_level', 'ssl_ca', 'ssl_enable', 'type', 'username', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': '', 'enforce_collate': 'auto', 'raw_sql_level': 'off', 'ssl_enable': 'off'},
        enum_restrictions={'enforce_collate': ['auto', 'on', 'off'], 'raw_sql_level': ['off', 'subselect', 'template', 'dashsql']},
    ),
    'promql': ConnectorMetadata(
        connector='promql',
        required=frozenset(['host', 'port']),
        available_fields=frozenset(['auth_header', 'auth_type', 'cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'host', 'name', 'password', 'path', 'port', 'secure', 'type', 'username', 'workbook_id']),
        defaults={'auth_type': 'password', 'data_export_forbidden': 'off', 'description': ''},
        enum_restrictions={},
    ),
    'smb_heatmaps': ConnectorMetadata(
        connector='smb_heatmaps',
        required=frozenset(['token']),
        available_fields=frozenset(['collection_id', 'description', 'dir_path', 'name', 'token', 'type', 'workbook_id']),
        defaults={'description': ''},
        enum_restrictions={},
    ),
    'snowflake': ConnectorMetadata(
        connector='snowflake',
        required=frozenset(['account_name', 'client_id', 'client_secret', 'db_name', 'schema', 'user_name', 'warehouse']),
        available_fields=frozenset(['account_name', 'client_id', 'client_secret', 'collection_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'name', 'raw_sql_level', 'refresh_token', 'refresh_token_expire_time', 'schema', 'type', 'user_name', 'user_role', 'warehouse', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': '', 'raw_sql_level': 'off'},
        enum_restrictions={'raw_sql_level': ['off', 'subselect', 'template', 'dashsql']},
    ),
    'speechsense': ConnectorMetadata(
        connector='speechsense',
        required=frozenset(['project_id']),
        available_fields=frozenset(['auth_type', 'cloud_id', 'collection_id', 'data_export_forbidden', 'delegation_is_set', 'description', 'dir_path', 'folder_id', 'name', 'project_id', 'service_account_id', 'type', 'workbook_id']),
        defaults={'auth_type': 'user_credentials', 'data_export_forbidden': 'off', 'description': ''},
        enum_restrictions={},
    ),
    'trino': ConnectorMetadata(
        connector='trino',
        required=frozenset(['host', 'listing_sources']),
        available_fields=frozenset(['auth_type', 'cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'cloud_id', 'collection_id', 'data_export_forbidden', 'db_name', 'delegation_is_set', 'description', 'dir_path', 'folder_id', 'host', 'jwt', 'listing_sources', 'mdb_cluster_id', 'name', 'password', 'port', 'raw_sql_level', 'service_account_id', 'ssl_ca', 'ssl_enable', 'type', 'username', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': '', 'raw_sql_level': 'off', 'ssl_enable': 'off'},
        enum_restrictions={'raw_sql_level': ['off', 'subselect', 'template', 'dashsql']},
    ),
    'usage_analytics_detailed': ConnectorMetadata(
        connector='usage_analytics_detailed',
        required=frozenset([]),
        available_fields=frozenset(['collection_id', 'description', 'dir_path', 'name', 'type', 'workbook_id']),
        defaults={'description': ''},
        enum_restrictions={},
    ),
    'usage_analytics_light': ConnectorMetadata(
        connector='usage_analytics_light',
        required=frozenset([]),
        available_fields=frozenset(['collection_id', 'description', 'dir_path', 'name', 'type', 'workbook_id']),
        defaults={'description': ''},
        enum_restrictions={},
    ),
    'ydb': ConnectorMetadata(
        connector='ydb',
        required=frozenset(['cloud_id', 'db_name', 'folder_id', 'host', 'port', 'service_account_id']),
        available_fields=frozenset(['auth_type', 'cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'cloud_id', 'collection_id', 'data_export_forbidden', 'db_name', 'delegation_is_set', 'description', 'dir_path', 'folder_id', 'host', 'mdb_cluster_id', 'mdb_folder_id', 'name', 'port', 'raw_sql_level', 'service_account_id', 'ssl_ca', 'ssl_enable', 'token', 'type', 'username', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': '', 'raw_sql_level': 'off', 'ssl_enable': 'on'},
        enum_restrictions={'auth_type': ['anonymous', 'password', 'oauth'], 'raw_sql_level': ['off', 'subselect', 'template', 'dashsql']},
    ),
    'yq': ConnectorMetadata(
        connector='yq',
        required=frozenset(['cloud_id', 'folder_id', 'service_account_id']),
        available_fields=frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'cloud_id', 'collection_id', 'data_export_forbidden', 'delegation_is_set', 'description', 'dir_path', 'folder_id', 'name', 'raw_sql_level', 'service_account_id', 'type', 'workbook_id']),
        defaults={'data_export_forbidden': 'off', 'description': '', 'raw_sql_level': 'off'},
        enum_restrictions={'raw_sql_level': ['off', 'subselect', 'template', 'dashsql']},
    ),
}

class AppmetricaApiConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='appmetrica_api',
            metadata=METADATA['appmetrica_api'],
            operations=operations,
        )

    def accuracy(self, value: float) -> Self:
        return self._set('accuracy', value)

    def counter_id(self, value: str) -> Self:
        return self._set('counter_id', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def token(self, value: str) -> Self:
        return self._set('token', value)

class BigqueryConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='bigquery',
            metadata=METADATA['bigquery'],
            operations=operations,
        )

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def credentials(self, value: str) -> Self:
        return self._set('credentials', value)

    def project_id(self, value: str) -> Self:
        return self._set('project_id', value)

    def raw_sql_level(self, value: Literal['off', 'subselect', 'template', 'dashsql']) -> Self:
        return self._set('raw_sql_level', value)

class Bitrix24ConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='bitrix24',
            metadata=METADATA['bitrix24'],
            operations=operations,
        )

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def portal(self, value: str) -> Self:
        return self._set('portal', value)

    def token(self, value: str) -> Self:
        return self._set('token', value)

class ChBillingAnalyticsConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='ch_billing_analytics',
            metadata=METADATA['ch_billing_analytics'],
            operations=operations,
        )

class ChYaMusicPodcastStatsConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='ch_ya_music_podcast_stats',
            metadata=METADATA['ch_ya_music_podcast_stats'],
            operations=operations,
        )

    def token(self, value: str) -> Self:
        return self._set('token', value)

class ChytConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='chyt',
            metadata=METADATA['chyt'],
            operations=operations,
        )

    def alias(self, value: str) -> Self:
        return self._set('alias', value)

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def host(self, value: str) -> Self:
        return self._set('host', value)

    def port(self, value: int) -> Self:
        return self._set('port', value)

    def raw_sql_level(self, value: Literal['off', 'subselect', 'template', 'dashsql']) -> Self:
        return self._set('raw_sql_level', value)

    def secure(self, value: bool) -> Self:
        return self._set('secure', value)

    def token(self, value: str) -> Self:
        return self._set('token', value)

class ClickhouseConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='clickhouse',
            metadata=METADATA['clickhouse'],
            operations=operations,
        )

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def connection_manager_cloud_id(self, value: str) -> Self:
        return self._set('connection_manager_cloud_id', value)

    def connection_manager_connection_id(self, value: str) -> Self:
        return self._set('connection_manager_connection_id', value)

    def connection_manager_delegation_is_set(self, value: bool) -> Self:
        return self._set('connection_manager_delegation_is_set', value)

    def connection_manager_folder_id(self, value: str) -> Self:
        return self._set('connection_manager_folder_id', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def db_name(self, value: str) -> Self:
        return self._set('db_name', value)

    def experimental_features(self, value: str) -> Self:
        return self._set('experimental_features', value)

    def host(self, value: str) -> Self:
        return self._set('host', value)

    def mdb_cluster_id(self, value: str) -> Self:
        return self._set('mdb_cluster_id', value)

    def mdb_folder_id(self, value: str) -> Self:
        return self._set('mdb_folder_id', value)

    def password(self, value: str) -> Self:
        return self._set('password', value)

    def port(self, value: int) -> Self:
        return self._set('port', value)

    def raw_sql_level(self, value: Literal['off', 'subselect', 'template', 'dashsql']) -> Self:
        return self._set('raw_sql_level', value)

    def readonly(self, value: int) -> Self:
        return self._set('readonly', value)

    def secure(self, value: Mapping[str, object]) -> Self:
        return self._set('secure', value)

    def ssl_ca(self, value: Mapping[str, object]) -> Self:
        return self._set('ssl_ca', value)

    def ssl_ca_verify(self, value: str) -> Self:
        return self._set('ssl_ca_verify', value)

    def username(self, value: str) -> Self:
        return self._set('username', value)

class EqueoConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='equeo',
            metadata=METADATA['equeo'],
            operations=operations,
        )

    def access_token(self, value: str) -> Self:
        return self._set('access_token', value)

class Extractor1cConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='extractor1c',
            metadata=METADATA['extractor1c'],
            operations=operations,
        )

    def access_token(self, value: str) -> Self:
        return self._set('access_token', value)

class GreenplumConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='greenplum',
            metadata=METADATA['greenplum'],
            operations=operations,
        )

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def db_name(self, value: str) -> Self:
        return self._set('db_name', value)

    def enforce_collate(self, value: Literal['auto', 'on', 'off']) -> Self:
        return self._set('enforce_collate', value)

    def host(self, value: str) -> Self:
        return self._set('host', value)

    def mdb_cluster_id(self, value: str) -> Self:
        return self._set('mdb_cluster_id', value)

    def mdb_folder_id(self, value: str) -> Self:
        return self._set('mdb_folder_id', value)

    def password(self, value: str) -> Self:
        return self._set('password', value)

    def port(self, value: int) -> Self:
        return self._set('port', value)

    def raw_sql_level(self, value: Literal['off', 'subselect', 'template', 'dashsql']) -> Self:
        return self._set('raw_sql_level', value)

    def ssl_ca(self, value: Mapping[str, object]) -> Self:
        return self._set('ssl_ca', value)

    def ssl_enable(self, value: str) -> Self:
        return self._set('ssl_enable', value)

    def username(self, value: str) -> Self:
        return self._set('username', value)

class GsheetsConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='gsheets',
            metadata=METADATA['gsheets'],
            operations=operations,
        )

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def url(self, value: str) -> Self:
        return self._set('url', value)

class JsonApiConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='json_api',
            metadata=METADATA['json_api'],
            operations=operations,
        )

    def allowed_methods(self, value: Sequence[object]) -> Self:
        return self._set('allowed_methods', value)

    def host(self, value: str) -> Self:
        return self._set('host', value)

    def path(self, value: str) -> Self:
        return self._set('path', value)

    def plain_headers(self, value: Mapping[str, object]) -> Self:
        return self._set('plain_headers', value)

    def port(self, value: int) -> Self:
        return self._set('port', value)

    def secret_headers(self, value: Mapping[str, object]) -> Self:
        return self._set('secret_headers', value)

    def secure(self, value: bool) -> Self:
        return self._set('secure', value)

class KonturMarketConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='kontur_market',
            metadata=METADATA['kontur_market'],
            operations=operations,
        )

    def access_token(self, value: str) -> Self:
        return self._set('access_token', value)

class MetrikaApiConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='metrika_api',
            metadata=METADATA['metrika_api'],
            operations=operations,
        )

    def accuracy(self, value: float) -> Self:
        return self._set('accuracy', value)

    def counter_id(self, value: str) -> Self:
        return self._set('counter_id', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def token(self, value: str) -> Self:
        return self._set('token', value)

class MonitoringConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='monitoring',
            metadata=METADATA['monitoring'],
            operations=operations,
        )

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def cloud_id(self, value: str) -> Self:
        return self._set('cloud_id', value)

    def delegation_is_set(self, value: bool) -> Self:
        return self._set('delegation_is_set', value)

    def folder_id(self, value: str) -> Self:
        return self._set('folder_id', value)

    def service_account_id(self, value: str) -> Self:
        return self._set('service_account_id', value)

class MoyskladConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='moysklad',
            metadata=METADATA['moysklad'],
            operations=operations,
        )

    def access_token(self, value: str) -> Self:
        return self._set('access_token', value)

class MssqlConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='mssql',
            metadata=METADATA['mssql'],
            operations=operations,
        )

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def db_name(self, value: str) -> Self:
        return self._set('db_name', value)

    def host(self, value: str) -> Self:
        return self._set('host', value)

    def password(self, value: str) -> Self:
        return self._set('password', value)

    def port(self, value: int) -> Self:
        return self._set('port', value)

    def raw_sql_level(self, value: Literal['off', 'subselect', 'template', 'dashsql']) -> Self:
        return self._set('raw_sql_level', value)

    def username(self, value: str) -> Self:
        return self._set('username', value)

class MysqlConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='mysql',
            metadata=METADATA['mysql'],
            operations=operations,
        )

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def connection_manager_cloud_id(self, value: str) -> Self:
        return self._set('connection_manager_cloud_id', value)

    def connection_manager_connection_id(self, value: str) -> Self:
        return self._set('connection_manager_connection_id', value)

    def connection_manager_delegation_is_set(self, value: bool) -> Self:
        return self._set('connection_manager_delegation_is_set', value)

    def connection_manager_folder_id(self, value: str) -> Self:
        return self._set('connection_manager_folder_id', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def db_name(self, value: str) -> Self:
        return self._set('db_name', value)

    def enforce_collate(self, value: Literal['auto', 'on', 'off']) -> Self:
        return self._set('enforce_collate', value)

    def host(self, value: str) -> Self:
        return self._set('host', value)

    def mdb_cluster_id(self, value: str) -> Self:
        return self._set('mdb_cluster_id', value)

    def mdb_folder_id(self, value: str) -> Self:
        return self._set('mdb_folder_id', value)

    def password(self, value: str) -> Self:
        return self._set('password', value)

    def port(self, value: int) -> Self:
        return self._set('port', value)

    def raw_sql_level(self, value: Literal['off', 'subselect', 'template', 'dashsql']) -> Self:
        return self._set('raw_sql_level', value)

    def ssl_ca(self, value: Mapping[str, object]) -> Self:
        return self._set('ssl_ca', value)

    def ssl_enable(self, value: str) -> Self:
        return self._set('ssl_enable', value)

    def username(self, value: str) -> Self:
        return self._set('username', value)

class OracleConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='oracle',
            metadata=METADATA['oracle'],
            operations=operations,
        )

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def db_connect_method(self, value: Literal['sid', 'service_name']) -> Self:
        return self._set('db_connect_method', value)

    def db_name(self, value: str) -> Self:
        return self._set('db_name', value)

    def host(self, value: str) -> Self:
        return self._set('host', value)

    def password(self, value: str) -> Self:
        return self._set('password', value)

    def port(self, value: int) -> Self:
        return self._set('port', value)

    def raw_sql_level(self, value: Literal['off', 'subselect', 'template', 'dashsql']) -> Self:
        return self._set('raw_sql_level', value)

    def ssl_ca(self, value: Mapping[str, object]) -> Self:
        return self._set('ssl_ca', value)

    def ssl_enable(self, value: str) -> Self:
        return self._set('ssl_enable', value)

    def username(self, value: str) -> Self:
        return self._set('username', value)

class PostgresConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='postgres',
            metadata=METADATA['postgres'],
            operations=operations,
        )

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def connection_manager_cloud_id(self, value: str) -> Self:
        return self._set('connection_manager_cloud_id', value)

    def connection_manager_connection_id(self, value: str) -> Self:
        return self._set('connection_manager_connection_id', value)

    def connection_manager_delegation_is_set(self, value: bool) -> Self:
        return self._set('connection_manager_delegation_is_set', value)

    def connection_manager_folder_id(self, value: str) -> Self:
        return self._set('connection_manager_folder_id', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def db_name(self, value: str) -> Self:
        return self._set('db_name', value)

    def enforce_collate(self, value: Literal['auto', 'on', 'off']) -> Self:
        return self._set('enforce_collate', value)

    def host(self, value: str) -> Self:
        return self._set('host', value)

    def mdb_cluster_id(self, value: str) -> Self:
        return self._set('mdb_cluster_id', value)

    def mdb_folder_id(self, value: str) -> Self:
        return self._set('mdb_folder_id', value)

    def password(self, value: str) -> Self:
        return self._set('password', value)

    def port(self, value: int) -> Self:
        return self._set('port', value)

    def raw_sql_level(self, value: Literal['off', 'subselect', 'template', 'dashsql']) -> Self:
        return self._set('raw_sql_level', value)

    def ssl_ca(self, value: Mapping[str, object]) -> Self:
        return self._set('ssl_ca', value)

    def ssl_enable(self, value: str) -> Self:
        return self._set('ssl_enable', value)

    def username(self, value: str) -> Self:
        return self._set('username', value)

class PromqlConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='promql',
            metadata=METADATA['promql'],
            operations=operations,
        )

    def auth_header(self, value: str) -> Self:
        return self._set('auth_header', value)

    def auth_type(self, value: str) -> Self:
        return self._set('auth_type', value)

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def db_name(self, value: str) -> Self:
        return self._set('db_name', value)

    def host(self, value: str) -> Self:
        return self._set('host', value)

    def password(self, value: str) -> Self:
        return self._set('password', value)

    def path(self, value: str) -> Self:
        return self._set('path', value)

    def port(self, value: int) -> Self:
        return self._set('port', value)

    def secure(self, value: bool) -> Self:
        return self._set('secure', value)

    def username(self, value: str) -> Self:
        return self._set('username', value)

class SmbHeatmapsConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='smb_heatmaps',
            metadata=METADATA['smb_heatmaps'],
            operations=operations,
        )

    def token(self, value: str) -> Self:
        return self._set('token', value)

class SnowflakeConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='snowflake',
            metadata=METADATA['snowflake'],
            operations=operations,
        )

    def account_name(self, value: str) -> Self:
        return self._set('account_name', value)

    def client_id(self, value: str) -> Self:
        return self._set('client_id', value)

    def client_secret(self, value: str) -> Self:
        return self._set('client_secret', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def db_name(self, value: str) -> Self:
        return self._set('db_name', value)

    def raw_sql_level(self, value: Literal['off', 'subselect', 'template', 'dashsql']) -> Self:
        return self._set('raw_sql_level', value)

    def refresh_token(self, value: str) -> Self:
        return self._set('refresh_token', value)

    def refresh_token_expire_time(self, value: str) -> Self:
        return self._set('refresh_token_expire_time', value)

    def schema(self, value: str) -> Self:
        return self._set('schema', value)

    def user_name(self, value: str) -> Self:
        return self._set('user_name', value)

    def user_role(self, value: str) -> Self:
        return self._set('user_role', value)

    def warehouse(self, value: str) -> Self:
        return self._set('warehouse', value)

class SpeechsenseConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='speechsense',
            metadata=METADATA['speechsense'],
            operations=operations,
        )

    def auth_type(self, value: str) -> Self:
        return self._set('auth_type', value)

    def cloud_id(self, value: str) -> Self:
        return self._set('cloud_id', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def delegation_is_set(self, value: bool) -> Self:
        return self._set('delegation_is_set', value)

    def folder_id(self, value: str) -> Self:
        return self._set('folder_id', value)

    def project_id(self, value: str) -> Self:
        return self._set('project_id', value)

    def service_account_id(self, value: str) -> Self:
        return self._set('service_account_id', value)

class TrinoConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='trino',
            metadata=METADATA['trino'],
            operations=operations,
        )

    def auth_type(self, value: Mapping[str, object]) -> Self:
        return self._set('auth_type', value)

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def cloud_id(self, value: str) -> Self:
        return self._set('cloud_id', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def db_name(self, value: str) -> Self:
        return self._set('db_name', value)

    def delegation_is_set(self, value: bool) -> Self:
        return self._set('delegation_is_set', value)

    def folder_id(self, value: str) -> Self:
        return self._set('folder_id', value)

    def host(self, value: str) -> Self:
        return self._set('host', value)

    def jwt(self, value: str) -> Self:
        return self._set('jwt', value)

    def listing_sources(self, value: Mapping[str, object]) -> Self:
        return self._set('listing_sources', value)

    def mdb_cluster_id(self, value: str) -> Self:
        return self._set('mdb_cluster_id', value)

    def password(self, value: str) -> Self:
        return self._set('password', value)

    def port(self, value: int) -> Self:
        return self._set('port', value)

    def raw_sql_level(self, value: Literal['off', 'subselect', 'template', 'dashsql']) -> Self:
        return self._set('raw_sql_level', value)

    def service_account_id(self, value: str) -> Self:
        return self._set('service_account_id', value)

    def ssl_ca(self, value: Mapping[str, object]) -> Self:
        return self._set('ssl_ca', value)

    def ssl_enable(self, value: str) -> Self:
        return self._set('ssl_enable', value)

    def username(self, value: str) -> Self:
        return self._set('username', value)

class UsageAnalyticsDetailedConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='usage_analytics_detailed',
            metadata=METADATA['usage_analytics_detailed'],
            operations=operations,
        )

class UsageAnalyticsLightConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='usage_analytics_light',
            metadata=METADATA['usage_analytics_light'],
            operations=operations,
        )

class YdbConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='ydb',
            metadata=METADATA['ydb'],
            operations=operations,
        )

    def auth_type(self, value: Literal['anonymous', 'password', 'oauth']) -> Self:
        return self._set('auth_type', value)

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def cloud_id(self, value: str) -> Self:
        return self._set('cloud_id', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def db_name(self, value: str) -> Self:
        return self._set('db_name', value)

    def delegation_is_set(self, value: bool) -> Self:
        return self._set('delegation_is_set', value)

    def folder_id(self, value: str) -> Self:
        return self._set('folder_id', value)

    def host(self, value: str) -> Self:
        return self._set('host', value)

    def mdb_cluster_id(self, value: str) -> Self:
        return self._set('mdb_cluster_id', value)

    def mdb_folder_id(self, value: str) -> Self:
        return self._set('mdb_folder_id', value)

    def port(self, value: int) -> Self:
        return self._set('port', value)

    def raw_sql_level(self, value: Literal['off', 'subselect', 'template', 'dashsql']) -> Self:
        return self._set('raw_sql_level', value)

    def service_account_id(self, value: str) -> Self:
        return self._set('service_account_id', value)

    def ssl_ca(self, value: Mapping[str, object]) -> Self:
        return self._set('ssl_ca', value)

    def ssl_enable(self, value: str) -> Self:
        return self._set('ssl_enable', value)

    def token(self, value: str) -> Self:
        return self._set('token', value)

    def username(self, value: str) -> Self:
        return self._set('username', value)

class YqConnectionCreate(BaseConnectionCreate):
    def __init__(self, *, name: str, location: EntryLocation, operations: ConnectionOperations | None = None) -> None:
        super().__init__(
            installation=INSTALLATION,
            location=location,
            name=name,
            connector='yq',
            metadata=METADATA['yq'],
            operations=operations,
        )

    def cache_invalidation_throttling_interval_sec(self, value: int) -> Self:
        return self._set('cache_invalidation_throttling_interval_sec', value)

    def cache_ttl_sec(self, value: int) -> Self:
        return self._set('cache_ttl_sec', value)

    def cloud_id(self, value: str) -> Self:
        return self._set('cloud_id', value)

    def data_export_forbidden(self, value: str) -> Self:
        return self._set('data_export_forbidden', value)

    def delegation_is_set(self, value: bool) -> Self:
        return self._set('delegation_is_set', value)

    def folder_id(self, value: str) -> Self:
        return self._set('folder_id', value)

    def raw_sql_level(self, value: Literal['off', 'subselect', 'template', 'dashsql']) -> Self:
        return self._set('raw_sql_level', value)

    def service_account_id(self, value: str) -> Self:
        return self._set('service_account_id', value)

class ConnectionCreateFactory:
    def __init__(self, operations: ConnectionOperations) -> None:
        self._operations = operations

    def appmetrica_api(self, *, name: str, location: EntryLocation) -> AppmetricaApiConnectionCreate:
        return AppmetricaApiConnectionCreate(name=name, location=location, operations=self._operations)

    def bigquery(self, *, name: str, location: EntryLocation) -> BigqueryConnectionCreate:
        return BigqueryConnectionCreate(name=name, location=location, operations=self._operations)

    def bitrix24(self, *, name: str, location: EntryLocation) -> Bitrix24ConnectionCreate:
        return Bitrix24ConnectionCreate(name=name, location=location, operations=self._operations)

    def ch_billing_analytics(self, *, name: str, location: EntryLocation) -> ChBillingAnalyticsConnectionCreate:
        return ChBillingAnalyticsConnectionCreate(name=name, location=location, operations=self._operations)

    def ch_ya_music_podcast_stats(self, *, name: str, location: EntryLocation) -> ChYaMusicPodcastStatsConnectionCreate:
        return ChYaMusicPodcastStatsConnectionCreate(name=name, location=location, operations=self._operations)

    def chyt(self, *, name: str, location: EntryLocation) -> ChytConnectionCreate:
        return ChytConnectionCreate(name=name, location=location, operations=self._operations)

    def clickhouse(self, *, name: str, location: EntryLocation) -> ClickhouseConnectionCreate:
        return ClickhouseConnectionCreate(name=name, location=location, operations=self._operations)

    def equeo(self, *, name: str, location: EntryLocation) -> EqueoConnectionCreate:
        return EqueoConnectionCreate(name=name, location=location, operations=self._operations)

    def extractor1c(self, *, name: str, location: EntryLocation) -> Extractor1cConnectionCreate:
        return Extractor1cConnectionCreate(name=name, location=location, operations=self._operations)

    def greenplum(self, *, name: str, location: EntryLocation) -> GreenplumConnectionCreate:
        return GreenplumConnectionCreate(name=name, location=location, operations=self._operations)

    def gsheets(self, *, name: str, location: EntryLocation) -> GsheetsConnectionCreate:
        return GsheetsConnectionCreate(name=name, location=location, operations=self._operations)

    def json_api(self, *, name: str, location: EntryLocation) -> JsonApiConnectionCreate:
        return JsonApiConnectionCreate(name=name, location=location, operations=self._operations)

    def kontur_market(self, *, name: str, location: EntryLocation) -> KonturMarketConnectionCreate:
        return KonturMarketConnectionCreate(name=name, location=location, operations=self._operations)

    def metrika_api(self, *, name: str, location: EntryLocation) -> MetrikaApiConnectionCreate:
        return MetrikaApiConnectionCreate(name=name, location=location, operations=self._operations)

    def monitoring(self, *, name: str, location: EntryLocation) -> MonitoringConnectionCreate:
        return MonitoringConnectionCreate(name=name, location=location, operations=self._operations)

    def moysklad(self, *, name: str, location: EntryLocation) -> MoyskladConnectionCreate:
        return MoyskladConnectionCreate(name=name, location=location, operations=self._operations)

    def mssql(self, *, name: str, location: EntryLocation) -> MssqlConnectionCreate:
        return MssqlConnectionCreate(name=name, location=location, operations=self._operations)

    def mysql(self, *, name: str, location: EntryLocation) -> MysqlConnectionCreate:
        return MysqlConnectionCreate(name=name, location=location, operations=self._operations)

    def oracle(self, *, name: str, location: EntryLocation) -> OracleConnectionCreate:
        return OracleConnectionCreate(name=name, location=location, operations=self._operations)

    def postgres(self, *, name: str, location: EntryLocation) -> PostgresConnectionCreate:
        return PostgresConnectionCreate(name=name, location=location, operations=self._operations)

    def promql(self, *, name: str, location: EntryLocation) -> PromqlConnectionCreate:
        return PromqlConnectionCreate(name=name, location=location, operations=self._operations)

    def smb_heatmaps(self, *, name: str, location: EntryLocation) -> SmbHeatmapsConnectionCreate:
        return SmbHeatmapsConnectionCreate(name=name, location=location, operations=self._operations)

    def snowflake(self, *, name: str, location: EntryLocation) -> SnowflakeConnectionCreate:
        return SnowflakeConnectionCreate(name=name, location=location, operations=self._operations)

    def speechsense(self, *, name: str, location: EntryLocation) -> SpeechsenseConnectionCreate:
        return SpeechsenseConnectionCreate(name=name, location=location, operations=self._operations)

    def trino(self, *, name: str, location: EntryLocation) -> TrinoConnectionCreate:
        return TrinoConnectionCreate(name=name, location=location, operations=self._operations)

    def usage_analytics_detailed(self, *, name: str, location: EntryLocation) -> UsageAnalyticsDetailedConnectionCreate:
        return UsageAnalyticsDetailedConnectionCreate(name=name, location=location, operations=self._operations)

    def usage_analytics_light(self, *, name: str, location: EntryLocation) -> UsageAnalyticsLightConnectionCreate:
        return UsageAnalyticsLightConnectionCreate(name=name, location=location, operations=self._operations)

    def ydb(self, *, name: str, location: EntryLocation) -> YdbConnectionCreate:
        return YdbConnectionCreate(name=name, location=location, operations=self._operations)

    def yq(self, *, name: str, location: EntryLocation) -> YqConnectionCreate:
        return YqConnectionCreate(name=name, location=location, operations=self._operations)
