# AUTOGENERATED by scripts/generate_sdk.py. Do not edit by hand.
# ruff: noqa
from __future__ import annotations

from collections.abc import Mapping
from typing import Literal
from pydantic import AliasChoices, BaseModel, ConfigDict, Field, model_validator

from datalens_sdk.domain.dataset_types import RawSchemaColumnPayload
from datalens_sdk.errors import NotSupportedError
from datalens_sdk.serialization.json_types import JsonValue

INSTALLATION_CONNECTORS: dict[str, frozenset[str]] = {
    'enterprise': frozenset(['appmetrica_api', 'chyt', 'clickhouse', 'greenplum', 'json_api', 'metrika_api', 'mssql', 'mysql', 'oracle', 'postgres', 'promql', 'trino', 'ydb']),
    'yacloud': frozenset(['appmetrica_api', 'bigquery', 'bitrix24', 'ch_billing_analytics', 'ch_ya_music_podcast_stats', 'chyt', 'clickhouse', 'equeo', 'extractor1c', 'greenplum', 'gsheets', 'json_api', 'kontur_market', 'metrika_api', 'monitoring', 'moysklad', 'mssql', 'mysql', 'oracle', 'postgres', 'promql', 'smb_heatmaps', 'snowflake', 'speechsense', 'trino', 'usage_analytics_detailed', 'usage_analytics_light', 'ydb', 'yq']),
}

CONNECTOR_FIELDS: dict[tuple[str, str], frozenset[str]] = {
    ('enterprise', 'appmetrica_api'): frozenset(['accuracy', 'collection_id', 'counter_id', 'data_export_forbidden', 'description', 'dir_path', 'name', 'token', 'type', 'workbook_id']),
    ('enterprise', 'chyt'): frozenset(['alias', 'cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'description', 'dir_path', 'host', 'name', 'port', 'raw_sql_level', 'secure', 'token', 'type', 'workbook_id']),
    ('enterprise', 'clickhouse'): frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'connection_manager_cloud_id', 'connection_manager_connection_id', 'connection_manager_delegation_is_set', 'connection_manager_folder_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'experimental_features', 'host', 'mdb_cluster_id', 'mdb_folder_id', 'name', 'password', 'port', 'raw_sql_level', 'readonly', 'secure', 'ssl_ca', 'ssl_ca_verify', 'type', 'username', 'workbook_id']),
    ('enterprise', 'greenplum'): frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'enforce_collate', 'host', 'mdb_cluster_id', 'mdb_folder_id', 'name', 'password', 'port', 'raw_sql_level', 'ssl_ca', 'ssl_enable', 'type', 'username', 'workbook_id']),
    ('enterprise', 'json_api'): frozenset(['allowed_methods', 'collection_id', 'description', 'dir_path', 'host', 'name', 'path', 'plain_headers', 'port', 'secret_headers', 'secure', 'type', 'workbook_id']),
    ('enterprise', 'metrika_api'): frozenset(['accuracy', 'collection_id', 'counter_id', 'data_export_forbidden', 'description', 'dir_path', 'name', 'token', 'type', 'workbook_id']),
    ('enterprise', 'mssql'): frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'host', 'name', 'password', 'port', 'raw_sql_level', 'type', 'username', 'workbook_id']),
    ('enterprise', 'mysql'): frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'connection_manager_cloud_id', 'connection_manager_connection_id', 'connection_manager_delegation_is_set', 'connection_manager_folder_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'enforce_collate', 'host', 'mdb_cluster_id', 'mdb_folder_id', 'name', 'password', 'port', 'raw_sql_level', 'ssl_ca', 'ssl_enable', 'type', 'username', 'workbook_id']),
    ('enterprise', 'oracle'): frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'db_connect_method', 'db_name', 'description', 'dir_path', 'host', 'name', 'password', 'port', 'raw_sql_level', 'ssl_ca', 'ssl_enable', 'type', 'username', 'workbook_id']),
    ('enterprise', 'postgres'): frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'connection_manager_cloud_id', 'connection_manager_connection_id', 'connection_manager_delegation_is_set', 'connection_manager_folder_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'enforce_collate', 'host', 'mdb_cluster_id', 'mdb_folder_id', 'name', 'password', 'port', 'raw_sql_level', 'ssl_ca', 'ssl_enable', 'type', 'username', 'workbook_id']),
    ('enterprise', 'promql'): frozenset(['auth_header', 'auth_type', 'cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'host', 'name', 'password', 'path', 'port', 'secure', 'type', 'username', 'workbook_id']),
    ('enterprise', 'trino'): frozenset(['auth_type', 'cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'cloud_id', 'collection_id', 'data_export_forbidden', 'db_name', 'delegation_is_set', 'description', 'dir_path', 'folder_id', 'host', 'jwt', 'listing_sources', 'mdb_cluster_id', 'name', 'password', 'port', 'raw_sql_level', 'service_account_id', 'ssl_ca', 'ssl_enable', 'type', 'username', 'workbook_id']),
    ('enterprise', 'ydb'): frozenset(['auth_type', 'cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'cloud_id', 'collection_id', 'data_export_forbidden', 'db_name', 'delegation_is_set', 'description', 'dir_path', 'folder_id', 'host', 'mdb_cluster_id', 'mdb_folder_id', 'name', 'port', 'raw_sql_level', 'service_account_id', 'ssl_ca', 'ssl_enable', 'token', 'type', 'username', 'workbook_id']),
    ('yacloud', 'appmetrica_api'): frozenset(['accuracy', 'collection_id', 'counter_id', 'data_export_forbidden', 'description', 'dir_path', 'name', 'token', 'type', 'workbook_id']),
    ('yacloud', 'bigquery'): frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'credentials', 'description', 'dir_path', 'name', 'project_id', 'raw_sql_level', 'type', 'workbook_id']),
    ('yacloud', 'bitrix24'): frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'description', 'dir_path', 'name', 'portal', 'token', 'type', 'workbook_id']),
    ('yacloud', 'ch_billing_analytics'): frozenset(['collection_id', 'description', 'dir_path', 'name', 'type', 'workbook_id']),
    ('yacloud', 'ch_ya_music_podcast_stats'): frozenset(['collection_id', 'description', 'dir_path', 'name', 'token', 'type', 'workbook_id']),
    ('yacloud', 'chyt'): frozenset(['alias', 'cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'description', 'dir_path', 'host', 'name', 'port', 'raw_sql_level', 'secure', 'token', 'type', 'workbook_id']),
    ('yacloud', 'clickhouse'): frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'connection_manager_cloud_id', 'connection_manager_connection_id', 'connection_manager_delegation_is_set', 'connection_manager_folder_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'experimental_features', 'host', 'mdb_cluster_id', 'mdb_folder_id', 'name', 'password', 'port', 'raw_sql_level', 'readonly', 'secure', 'ssl_ca', 'ssl_ca_verify', 'type', 'username', 'workbook_id']),
    ('yacloud', 'equeo'): frozenset(['access_token', 'collection_id', 'description', 'dir_path', 'name', 'type', 'workbook_id']),
    ('yacloud', 'extractor1c'): frozenset(['access_token', 'collection_id', 'description', 'dir_path', 'name', 'type', 'workbook_id']),
    ('yacloud', 'greenplum'): frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'enforce_collate', 'host', 'mdb_cluster_id', 'mdb_folder_id', 'name', 'password', 'port', 'raw_sql_level', 'ssl_ca', 'ssl_enable', 'type', 'username', 'workbook_id']),
    ('yacloud', 'gsheets'): frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'description', 'dir_path', 'name', 'type', 'url', 'workbook_id']),
    ('yacloud', 'json_api'): frozenset(['allowed_methods', 'collection_id', 'description', 'dir_path', 'host', 'name', 'path', 'plain_headers', 'port', 'secret_headers', 'secure', 'type', 'workbook_id']),
    ('yacloud', 'kontur_market'): frozenset(['access_token', 'collection_id', 'description', 'dir_path', 'name', 'type', 'workbook_id']),
    ('yacloud', 'metrika_api'): frozenset(['accuracy', 'collection_id', 'counter_id', 'data_export_forbidden', 'description', 'dir_path', 'name', 'token', 'type', 'workbook_id']),
    ('yacloud', 'monitoring'): frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'cloud_id', 'collection_id', 'delegation_is_set', 'description', 'dir_path', 'folder_id', 'name', 'service_account_id', 'type', 'workbook_id']),
    ('yacloud', 'moysklad'): frozenset(['access_token', 'collection_id', 'description', 'dir_path', 'name', 'type', 'workbook_id']),
    ('yacloud', 'mssql'): frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'host', 'name', 'password', 'port', 'raw_sql_level', 'type', 'username', 'workbook_id']),
    ('yacloud', 'mysql'): frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'connection_manager_cloud_id', 'connection_manager_connection_id', 'connection_manager_delegation_is_set', 'connection_manager_folder_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'enforce_collate', 'host', 'mdb_cluster_id', 'mdb_folder_id', 'name', 'password', 'port', 'raw_sql_level', 'ssl_ca', 'ssl_enable', 'type', 'username', 'workbook_id']),
    ('yacloud', 'oracle'): frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'db_connect_method', 'db_name', 'description', 'dir_path', 'host', 'name', 'password', 'port', 'raw_sql_level', 'ssl_ca', 'ssl_enable', 'type', 'username', 'workbook_id']),
    ('yacloud', 'postgres'): frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'connection_manager_cloud_id', 'connection_manager_connection_id', 'connection_manager_delegation_is_set', 'connection_manager_folder_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'enforce_collate', 'host', 'mdb_cluster_id', 'mdb_folder_id', 'name', 'password', 'port', 'raw_sql_level', 'ssl_ca', 'ssl_enable', 'type', 'username', 'workbook_id']),
    ('yacloud', 'promql'): frozenset(['auth_header', 'auth_type', 'cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'collection_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'host', 'name', 'password', 'path', 'port', 'secure', 'type', 'username', 'workbook_id']),
    ('yacloud', 'smb_heatmaps'): frozenset(['collection_id', 'description', 'dir_path', 'name', 'token', 'type', 'workbook_id']),
    ('yacloud', 'snowflake'): frozenset(['account_name', 'client_id', 'client_secret', 'collection_id', 'data_export_forbidden', 'db_name', 'description', 'dir_path', 'name', 'raw_sql_level', 'refresh_token', 'refresh_token_expire_time', 'schema', 'type', 'user_name', 'user_role', 'warehouse', 'workbook_id']),
    ('yacloud', 'speechsense'): frozenset(['auth_type', 'cloud_id', 'collection_id', 'data_export_forbidden', 'delegation_is_set', 'description', 'dir_path', 'folder_id', 'name', 'project_id', 'service_account_id', 'type', 'workbook_id']),
    ('yacloud', 'trino'): frozenset(['auth_type', 'cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'cloud_id', 'collection_id', 'data_export_forbidden', 'db_name', 'delegation_is_set', 'description', 'dir_path', 'folder_id', 'host', 'jwt', 'listing_sources', 'mdb_cluster_id', 'name', 'password', 'port', 'raw_sql_level', 'service_account_id', 'ssl_ca', 'ssl_enable', 'type', 'username', 'workbook_id']),
    ('yacloud', 'usage_analytics_detailed'): frozenset(['collection_id', 'description', 'dir_path', 'name', 'type', 'workbook_id']),
    ('yacloud', 'usage_analytics_light'): frozenset(['collection_id', 'description', 'dir_path', 'name', 'type', 'workbook_id']),
    ('yacloud', 'ydb'): frozenset(['auth_type', 'cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'cloud_id', 'collection_id', 'data_export_forbidden', 'db_name', 'delegation_is_set', 'description', 'dir_path', 'folder_id', 'host', 'mdb_cluster_id', 'mdb_folder_id', 'name', 'port', 'raw_sql_level', 'service_account_id', 'ssl_ca', 'ssl_enable', 'token', 'type', 'username', 'workbook_id']),
    ('yacloud', 'yq'): frozenset(['cache_invalidation_throttling_interval_sec', 'cache_ttl_sec', 'cloud_id', 'collection_id', 'data_export_forbidden', 'delegation_is_set', 'description', 'dir_path', 'folder_id', 'name', 'raw_sql_level', 'service_account_id', 'type', 'workbook_id']),
}

INSTALLATION_SOURCES: dict[str, frozenset[str]] = {
    'enterprise': frozenset(['APPMETRICA_API', 'CHYT_YTSAURUS_SUBSELECT', 'CHYT_YTSAURUS_TABLE', 'CHYT_YTSAURUS_TABLE_LIST', 'CHYT_YTSAURUS_TABLE_RANGE', 'CH_SUBSELECT', 'CH_TABLE', 'GP_SUBSELECT', 'GP_TABLE', 'JSON_API', 'METRIKA_API', 'MSSQL_SUBSELECT', 'MSSQL_TABLE', 'MYSQL_SUBSELECT', 'MYSQL_TABLE', 'ORACLE_SUBSELECT', 'ORACLE_TABLE', 'PG_SUBSELECT', 'PG_TABLE', 'PROMQL', 'TRINO_SUBSELECT', 'TRINO_TABLE', 'YDB_SUBSELECT', 'YDB_TABLE']),
    'yacloud': frozenset(['APPMETRICA_API', 'BIGQUERY_SUBSELECT', 'BIGQUERY_TABLE', 'BITRIX_GDS', 'CHYT_YTSAURUS_SUBSELECT', 'CHYT_YTSAURUS_TABLE', 'CHYT_YTSAURUS_TABLE_LIST', 'CHYT_YTSAURUS_TABLE_RANGE', 'CH_BILLING_ANALYTICS_TABLE', 'CH_SMB_HEATMAPS_TABLE', 'CH_SUBSELECT', 'CH_TABLE', 'CH_USAGE_TRACKING_AGG_TABLE', 'CH_USAGE_TRACKING_TABLE', 'CH_YA_MUSIC_PODCAST_STATS_TABLE', 'EQUEO_CH_TABLE', 'EXTRACTOR_1C_CH_TABLE', 'GP_SUBSELECT', 'GP_TABLE', 'GSHEETS', 'JSON_API', 'KONTUR_MARKET_CH_TABLE', 'METRIKA_API', 'MONITORING', 'MOYSKLAD_CH_TABLE', 'MSSQL_SUBSELECT', 'MSSQL_TABLE', 'MYSQL_SUBSELECT', 'MYSQL_TABLE', 'ORACLE_SUBSELECT', 'ORACLE_TABLE', 'PG_SUBSELECT', 'PG_TABLE', 'PROMQL', 'SNOWFLAKE_TABLE', 'SPEECHSENSE_TABLE', 'TRINO_SUBSELECT', 'TRINO_TABLE', 'YDB_SUBSELECT', 'YDB_TABLE', 'YQ_SUBSELECT', 'YQ_TABLE']),
}


class ConnectionCreateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    installation: str
    connection_type: str = Field(serialization_alias="connectionType")
    params: Mapping[str, object] = Field(repr=False)

    @model_validator(mode="after")
    def _validate_support(self) -> ConnectionCreateDTO:
        connectors = INSTALLATION_CONNECTORS.get(self.installation)
        if connectors is None or self.connection_type not in connectors:
            raise NotSupportedError(
                f"Connection type {self.connection_type!r} is not available on installation {self.installation!r}"
            )
        fields = CONNECTOR_FIELDS[(self.installation, self.connection_type)]
        unknown = sorted(set(self.params) - fields)
        if unknown:
            raise NotSupportedError(
                f"Fields {unknown} are not available for {self.connection_type!r} on {self.installation!r}"
            )
        return self

    def to_payload(self) -> dict[str, object]:
        payload = dict(self.params)
        payload["type"] = self.connection_type
        return payload


class ConnectionReadDTO(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: str | None = None
    type: str | None = None
    db_type: str | None = None
    name: str | None = None
    description: str | None = None
    key: str | None = None
    dir_path: str | None = None
    raw: dict[str, object] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def _capture_raw(cls, value: object) -> object:
        if isinstance(value, dict) and "raw" not in value:
            return {**value, "raw": value}
        return value


class DatasetSourceDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    id: str
    title: str
    source_type: str
    connection_id: str | None = None
    connection_type: str
    managed_by: str = "user"
    parameters: Mapping[str, object] = Field(default_factory=dict)
    raw_schema: tuple[RawSchemaColumnPayload, ...] = ()

    def to_payload(self) -> dict[str, object]:
        return {
            "id": self.id,
            "title": self.title,
            "source_type": self.source_type,
            "connection_id": self.connection_id,
            "connection_type": self.connection_type,
            "managed_by": self.managed_by,
            "parameters": dict(self.parameters),
            "raw_schema": [dict(field) for field in self.raw_schema],
        }


class DatasetContentDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    description: str = ""
    sources: tuple[DatasetSourceDTO, ...] = ()
    source_avatars: tuple[object, ...] = ()
    avatar_relations: tuple[object, ...] = ()
    result_schema: tuple[Mapping[str, object], ...] = ()
    obligatory_filters: tuple[Mapping[str, object], ...] = ()
    rls2: Mapping[str, object] | None = None

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {
            "description": self.description,
            "sources": [source.to_payload() for source in self.sources],
            "source_avatars": list(self.source_avatars),
            "avatar_relations": list(self.avatar_relations),
        }
        if self.result_schema:
            payload["result_schema"] = [dict(field) for field in self.result_schema]
        if self.obligatory_filters:
            payload["obligatory_filters"] = [dict(item) for item in self.obligatory_filters]
        if self.rls2 is not None:
            payload["rls2"] = dict(self.rls2)
        return payload


class DatasetCreateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    installation: str
    name: str
    dir_path: str | None = None
    workbook_id: str | None = None
    collection_id: str | None = None
    dataset: DatasetContentDTO

    @model_validator(mode="after")
    def _validate_sources(self) -> DatasetCreateDTO:
        available = INSTALLATION_SOURCES.get(self.installation, frozenset())
        for source in self.dataset.sources:
            if source.source_type not in available:
                raise NotSupportedError(
                    f"Dataset source {source.source_type!r} is not available on installation {self.installation!r}"
                )
        return self

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {"name": self.name, "dataset": self.dataset.to_payload()}
        if self.dir_path is not None:
            payload["dir_path"] = self.dir_path
        if self.workbook_id is not None:
            payload["workbook_id"] = self.workbook_id
        if self.collection_id is not None:
            payload["collection_id"] = self.collection_id
        return payload


class DatasetReadDTO(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: str | None = None
    name: str | None = None
    dir_path: str | None = None
    workbook_id: str | None = None
    collection_id: str | None = None
    key: str | None = None
    is_favorite: bool | None = None
    permissions: Mapping[str, object] | None = None
    full_permissions: Mapping[str, object] | None = None
    options: Mapping[str, object] | None = None
    published_id: str | None = Field(default=None, validation_alias="publishedId")
    rev_id: str | None = Field(default=None, validation_alias="revId")
    saved_id: str | None = Field(default=None, validation_alias="savedId")
    dataset: dict[str, object] | None = None
    raw: dict[str, object] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def _capture_raw(cls, value: object) -> object:
        if isinstance(value, dict) and "raw" not in value:
            return {**value, "raw": value}
        return value


class DatasetValidateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    dataset_id: str = Field(serialization_alias="datasetId")
    data: Mapping[str, object]

    def to_payload(self) -> dict[str, object]:
        return {"datasetId": self.dataset_id, "data": dict(self.data)}


class DatasetUpdateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    dataset_id: str = Field(serialization_alias="datasetId")
    data: Mapping[str, object]

    def to_payload(self) -> dict[str, object]:
        return {"datasetId": self.dataset_id, "data": dict(self.data)}


class EntryMoveDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    entry_id: str = Field(serialization_alias="entryId")
    destination: str
    name: str | None = None

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {"entryId": self.entry_id, "destination": self.destination}
        if self.name is not None:
            payload["name"] = self.name
        return payload


class EntryRenameDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    entry_id: str = Field(serialization_alias="entryId")
    name: str

    def to_payload(self) -> dict[str, object]:
        return {"entryId": self.entry_id, "name": self.name}


class CollectionCreateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    name: str = Field(serialization_alias="title")
    parent_id: str | None = Field(serialization_alias="parentId")
    description: str | None = None

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {"title": self.name, "parentId": self.parent_id}
        if self.description is not None:
            payload["description"] = self.description
        return payload


class CollectionReadDTO(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: str = Field(validation_alias="collectionId")
    name: str = Field(validation_alias="title")
    description: str | None = None
    parent_id: str | None = Field(default=None, validation_alias="parentId")
    tenant_id: str | None = Field(default=None, validation_alias="tenantId")
    created_by: str | None = Field(default=None, validation_alias="createdBy")
    created_at: str | None = Field(default=None, validation_alias="createdAt")
    updated_by: str | None = Field(default=None, validation_alias="updatedBy")
    updated_at: str | None = Field(default=None, validation_alias="updatedAt")
    meta: Mapping[str, object] | None = None
    permissions: Mapping[str, object] | None = None
    raw: dict[str, object] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def _capture_raw(cls, value: object) -> object:
        if isinstance(value, dict) and "raw" not in value:
            return {**value, "raw": value}
        return value


class CollectionUpdateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    id: str = Field(serialization_alias="collectionId")
    name: str | None = Field(default=None, serialization_alias="title")
    description: str | None = None

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {"collectionId": self.id}
        if self.name is not None:
            payload["title"] = self.name
        if self.description is not None:
            payload["description"] = self.description
        return payload


class CollectionMoveDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    id: str = Field(serialization_alias="collectionId")
    parent_id: str | None = Field(serialization_alias="parentId")
    name: str | None = Field(default=None, serialization_alias="title")

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {"collectionId": self.id, "parentId": self.parent_id}
        if self.name is not None:
            payload["title"] = self.name
        return payload


class WorkbookCreateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    name: str = Field(serialization_alias="title")
    collection_id: str | None = Field(default=None, serialization_alias="collectionId")
    description: str | None = None

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {"title": self.name}
        if self.collection_id is not None:
            payload["collectionId"] = self.collection_id
        if self.description is not None:
            payload["description"] = self.description
        return payload


class WorkbookReadDTO(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: str = Field(validation_alias="workbookId")
    name: str = Field(validation_alias="title")
    description: str | None = None
    collection_id: str | None = Field(default=None, validation_alias="collectionId")
    status: str | None = None
    tenant_id: str | None = Field(default=None, validation_alias="tenantId")
    created_by: str | None = Field(default=None, validation_alias="createdBy")
    created_at: str | None = Field(default=None, validation_alias="createdAt")
    updated_by: str | None = Field(default=None, validation_alias="updatedBy")
    updated_at: str | None = Field(default=None, validation_alias="updatedAt")
    meta: Mapping[str, object] | None = None
    permissions: Mapping[str, object] | None = None
    raw: dict[str, object] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def _capture_raw(cls, value: object) -> object:
        if isinstance(value, dict) and "raw" not in value:
            return {**value, "raw": value}
        return value


class WorkbookUpdateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    id: str = Field(serialization_alias="workbookId")
    name: str | None = Field(default=None, serialization_alias="title")
    description: str | None = None

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {"workbookId": self.id}
        if self.name is not None:
            payload["title"] = self.name
        if self.description is not None:
            payload["description"] = self.description
        return payload


class WorkbookMoveDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    id: str = Field(serialization_alias="workbookId")
    collection_id: str | None = Field(serialization_alias="collectionId")
    name: str | None = Field(default=None, serialization_alias="title")

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {"workbookId": self.id, "collectionId": self.collection_id}
        if self.name is not None:
            payload["title"] = self.name
        return payload


class FolderCreateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    key: str

    def to_payload(self) -> dict[str, object]:
        return {"key": self.key}


class FolderReadDTO(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: str = Field(validation_alias="entryId")
    name: str | None = None
    key: str
    scope: str
    created_by: str | None = Field(default=None, validation_alias="createdBy")
    created_at: str | None = Field(default=None, validation_alias="createdAt")
    updated_by: str | None = Field(default=None, validation_alias="updatedBy")
    updated_at: str | None = Field(default=None, validation_alias="updatedAt")
    hidden: bool = False
    meta: Mapping[str, object] | None = None
    raw: dict[str, object] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def _capture_raw(cls, value: object) -> object:
        if isinstance(value, dict) and "raw" not in value:
            return {**value, "raw": value}
        return value


class FolderGetResultDTO(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    entries: tuple[FolderReadDTO, ...]


class FolderUpdateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    id: str = Field(serialization_alias="entryId")
    name: str

    def to_payload(self) -> dict[str, object]:
        return {"entryId": self.id, "name": self.name}



class GetEntriesArgsDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    ids: tuple[str, ...] = ()
    created_by: tuple[str, ...] = ()
    name: str | None = None
    exclude_locked: bool | None = None
    ignore_shared_entries: bool | None = None
    ignore_workbook_entries: bool | None = None
    include_data: bool | None = None
    include_links: bool | None = None
    include_permissions_info: bool | None = None
    order_field: Literal["createdAt", "name"] | None = None
    order_direction: Literal["asc", "desc"] = "asc"
    page_size: int = Field(default=100, ge=1, le=200)
    page_token: str | None = None
    scope: str | None = None
    type: str | None = None

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {"pageSize": self.page_size}
        if self.ids:
            payload["ids"] = list(self.ids)
        if self.created_by:
            payload["createdBy"] = list(self.created_by)
        if self.name is not None:
            payload["filters"] = {"name": self.name}
        for key, value in (
            ("excludeLocked", self.exclude_locked),
            ("ignoreSharedEntries", self.ignore_shared_entries),
            ("ignoreWorkbookEntries", self.ignore_workbook_entries),
            ("includeData", self.include_data),
            ("includeLinks", self.include_links),
            ("includePermissionsInfo", self.include_permissions_info),
        ):
            if value is not None:
                payload[key] = value
        if self.order_field is not None:
            payload["orderBy"] = {"field": self.order_field, "direction": self.order_direction}
        if self.page_token is not None:
            payload["pageToken"] = self.page_token
        if self.scope is not None:
            payload["scope"] = self.scope
        if self.type is not None:
            payload["type"] = self.type
        return payload


class ListDirectoryArgsDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    path: str
    created_by: str | tuple[str, ...] | None = None
    name: str | None = None
    include_permissions_info: bool | None = None
    order_field: Literal["createdAt", "name"] | None = None
    order_direction: Literal["asc", "desc"] = "asc"
    page: int = Field(default=0, ge=0)
    page_size: int = Field(default=100, ge=1)

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {"path": self.path, "page": self.page, "pageSize": self.page_size}
        if self.created_by is not None:
            payload["createdBy"] = list(self.created_by) if isinstance(self.created_by, tuple) else self.created_by
        if self.name is not None:
            payload["filters"] = {"name": self.name}
        if self.include_permissions_info is not None:
            payload["includePermissionsInfo"] = self.include_permissions_info
        if self.order_field is not None:
            payload["orderBy"] = {"field": self.order_field, "direction": self.order_direction}
        return payload


class CollectionContentArgsDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    collection_id: str
    filter_string: str | None = None
    include_permissions_info: bool | None = None
    mode: Literal["all", "onlyCollections", "onlyWorkbooks", "onlyEntries"] = "all"
    only_my: bool | None = None
    order_field: Literal["title", "createdAt", "updatedAt"] | None = None
    order_direction: Literal["asc", "desc"] = "asc"
    page: str | None = None
    page_size: int = Field(default=100, ge=1)

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {
            "collectionId": self.collection_id,
            "mode": self.mode,
            "pageSize": self.page_size,
        }
        for key, value in (
            ("filterString", self.filter_string),
            ("includePermissionsInfo", self.include_permissions_info),
            ("onlyMy", self.only_my),
            ("page", self.page),
        ):
            if value is not None:
                payload[key] = value
        if self.order_field is not None:
            payload["orderField"] = self.order_field
            payload["orderDirection"] = self.order_direction
        return payload


class WorkbookEntriesArgsDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    workbook_id: str
    created_by: str | None = None
    name: str | None = None
    include_permissions_info: bool | None = None
    order_field: Literal["name", "createdAt"] | None = None
    order_direction: Literal["asc", "desc"] = "asc"
    page: int = Field(default=0, ge=0)
    page_size: int = Field(default=100, ge=1)
    scope: str | tuple[str, ...] | None = None

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {
            "workbookId": self.workbook_id,
            "page": self.page,
            "pageSize": self.page_size,
        }
        if self.created_by is not None:
            payload["createdBy"] = self.created_by
        if self.name is not None:
            payload["filters"] = {"name": self.name}
        if self.include_permissions_info is not None:
            payload["includePermissionsInfo"] = self.include_permissions_info
        if self.order_field is not None:
            payload["orderBy"] = {"field": self.order_field, "direction": self.order_direction}
        if self.scope is not None:
            payload["scope"] = list(self.scope) if isinstance(self.scope, tuple) else self.scope
        return payload


class EntryRelationsArgsDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    entry_ids: tuple[str, ...]
    include_permissions_info: bool | None = None
    link_direction: Literal["from", "to"] | None = None
    limit: int = Field(default=100, ge=1)
    page_token: str | None = None
    scope: Literal["dash", "report", "widget", "dataset", "folder", "connection"] | None = None

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {"entryIds": list(self.entry_ids), "limit": self.limit}
        for key, value in (
            ("includePermissionsInfo", self.include_permissions_info),
            ("linkDirection", self.link_direction),
            ("pageToken", self.page_token),
            ("scope", self.scope),
        ):
            if value is not None:
                payload[key] = value
        return payload


class EntrySummaryReadDTO(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: str = Field(validation_alias=AliasChoices("entryId", "id"))
    scope: str
    type: str
    name: str | None = Field(default=None, validation_alias=AliasChoices("name", "title", "displayKey"))
    key: str | None = None
    created_by: str | None = Field(default=None, validation_alias="createdBy")
    created_at: str | None = Field(default=None, validation_alias="createdAt")
    updated_by: str | None = Field(default=None, validation_alias="updatedBy")
    updated_at: str | None = Field(default=None, validation_alias="updatedAt")
    saved_id: str | None = Field(default=None, validation_alias="savedId")
    published_id: str | None = Field(default=None, validation_alias="publishedId")
    workbook_id: str | None = Field(default=None, validation_alias="workbookId")
    collection_id: str | None = Field(default=None, validation_alias="collectionId")
    hidden: bool | None = None
    is_favorite: bool | None = Field(default=None, validation_alias="isFavorite")
    is_locked: bool = Field(default=False, validation_alias="isLocked")
    meta: Mapping[str, object] | None = None
    permissions: Mapping[str, object] | None = None
    data: Mapping[str, object] | None = None
    links: Mapping[str, str] | None = None
    raw: dict[str, object] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def _capture_raw(cls, value: object) -> object:
        if isinstance(value, dict) and "raw" not in value:
            return {**value, "raw": value}
        return value


class GetEntriesResultDTO(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    entries: tuple[EntrySummaryReadDTO, ...]
    next_page_token: str | None = Field(default=None, validation_alias="nextPageToken")


class DirectoryBreadcrumbReadDTO(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: str = Field(validation_alias="entryId")
    name: str = Field(validation_alias="title")
    path: str
    is_locked: bool = Field(validation_alias="isLocked")
    permissions: Mapping[str, object]
    raw: dict[str, object] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def _capture_raw(cls, value: object) -> object:
        if isinstance(value, dict) and "raw" not in value:
            return {**value, "raw": value}
        return value


class ListDirectoryResultDTO(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    entries: tuple[EntrySummaryReadDTO, ...]
    breadcrumbs: tuple[DirectoryBreadcrumbReadDTO, ...] = Field(validation_alias="breadCrumbs")
    has_next_page: bool = Field(validation_alias="hasNextPage")


class CollectionSummaryReadDTO(CollectionReadDTO):
    entity: Literal["collection"]


class WorkbookSummaryReadDTO(WorkbookReadDTO):
    entity: Literal["workbook"]


class StructureEntrySummaryReadDTO(EntrySummaryReadDTO):
    entity: Literal["entry"]


class CollectionContentResultDTO(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    items: tuple[CollectionSummaryReadDTO | WorkbookSummaryReadDTO | StructureEntrySummaryReadDTO, ...]
    next_page_token: str | None = Field(default=None, validation_alias="nextPageToken")


class WorkbookEntriesResultDTO(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    entries: tuple[EntrySummaryReadDTO, ...]
    next_page_token: str | None = Field(default=None, validation_alias="nextPageToken")


class EntryRelationReadDTO(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: str = Field(validation_alias="entryId")
    scope: Literal["dash", "report", "widget", "dataset", "folder", "connection"]
    type: str
    key: str | None = None
    created_at: str | None = Field(default=None, validation_alias="createdAt")
    public: bool = False
    tenant_id: str | None = Field(default=None, validation_alias="tenantId")
    workbook_id: str | None = Field(default=None, validation_alias="workbookId")
    collection_id: str | None = Field(default=None, validation_alias="collectionId")
    is_locked: bool = Field(default=False, validation_alias="isLocked")
    permissions: Mapping[str, object] | None = None
    full_permissions: Mapping[str, object] | None = Field(default=None, validation_alias="fullPermissions")
    raw: dict[str, object] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def _capture_raw(cls, value: object) -> object:
        if isinstance(value, dict) and "raw" not in value:
            return {**value, "raw": value}
        return value


class EntryRelationsResultDTO(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    relations: tuple[EntryRelationReadDTO, ...]
    next_page_token: str | None = Field(default=None, validation_alias="nextPageToken")



class LicenseAssignArgsDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    user_ids: tuple[str, ...] = Field(serialization_alias="userIds", min_length=1, max_length=1000)

    def to_payload(self) -> dict[str, object]:
        return {"userIds": list(self.user_ids)}


class LicenseListArgsDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    user_ids: tuple[str, ...] = Field(default=(), serialization_alias="userIds", max_length=1000)
    status: Literal["active", "expired", "expiring"] | None = None
    sort_by: Literal["createdAt", "updatedAt"] | None = Field(default=None, serialization_alias="sortBy")
    order: Literal["asc", "desc"] = "asc"
    limit: int = Field(default=100, ge=1, le=200)
    page_token: str | None = Field(default=None, serialization_alias="pageToken")

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {"limit": self.limit, "order": self.order}
        if self.user_ids:
            payload["userIds"] = list(self.user_ids)
        if self.status is not None:
            payload["status"] = self.status
        if self.sort_by is not None:
            payload["sortBy"] = self.sort_by
        if self.page_token is not None:
            payload["pageToken"] = self.page_token
        return payload


class LicenseReadDTO(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    license_id: str = Field(validation_alias="licenseId")
    user_id: str = Field(validation_alias="userId")
    tenant_id: str = Field(validation_alias="tenantId")
    license_type: Literal["creator"] = Field(validation_alias="licenseType")
    is_active: bool = Field(validation_alias="isActive")
    expires_at: str | None = Field(validation_alias="expiresAt")
    created_by: str = Field(validation_alias="createdBy")
    created_at: str = Field(validation_alias="createdAt")
    updated_by: str = Field(validation_alias="updatedBy")
    updated_at: str = Field(validation_alias="updatedAt")
    last_login_at: str | None = Field(default=None, validation_alias="lastLoginAt")
    meta: Mapping[str, object]
    raw: dict[str, object] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def _capture_raw(cls, value: object) -> object:
        if isinstance(value, dict) and "raw" not in value:
            return {**value, "raw": value}
        return value


class LicenseWithLastLoginReadDTO(LicenseReadDTO):
    last_login_at: str | None = Field(validation_alias="lastLoginAt")


class LicenseListResultDTO(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    licenses: tuple[LicenseWithLastLoginReadDTO, ...]
    next_page_token: str | None = Field(default=None, validation_alias="nextPageToken")


class LicenseLimitReadDTO(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type: Literal["regular", "forced"]
    value: int
    started_at: str = Field(validation_alias="startedAt")
    active_licenses_count: int | None = Field(validation_alias="activeLicensesCount")


class LicenseLimitsReadDTO(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    current: LicenseLimitReadDTO | None
    next: LicenseLimitReadDTO | None


class LicenseSetLimitArgsDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    value: int = Field(ge=1, le=10000)

    def to_payload(self) -> dict[str, object]:
        return {"value": self.value}

INSTALLATION_EDITOR_NODE_TYPES: dict[str, frozenset[str]] = {
    'enterprise': frozenset(['advanced-chart_node', 'control_node', 'd3_node', 'markdown_node', 'table_node']),
    'yacloud': frozenset(['advanced-chart_node', 'control_node', 'd3_node', 'markdown_node', 'table_node']),
}


WIZARD_SCHEMA_FINGERPRINT: str | None = None
WIZARD_DTO_BINDINGS: dict[str, dict[str, str | None]] = {}




def _validate_wizard_v1_line_config(data: Mapping[str, JsonValue]) -> None:
    sources = data.get("sources")
    visualization = data.get("visualization")
    if not isinstance(sources, Mapping) or not isinstance(sources.get("datasetsIds"), list):
        raise ValueError("Wizard V1 config sources.datasetsIds must be an array")
    if not isinstance(visualization, Mapping) or visualization.get("type") != "line":
        raise ValueError("Wizard V1 config visualization.type must be 'line'")
    x_slot = visualization.get("x")
    if not isinstance(x_slot, Mapping) or not isinstance(x_slot.get("items"), list):
        raise ValueError("Wizard V1 line visualization.x.items must be an array")


class WizardChartCreateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    data: dict[str, JsonValue]
    key: str | None = None
    name: str | None = None
    workbook_id: str | None = Field(default=None, serialization_alias="workbookId")
    annotation: dict[str, JsonValue] | None = None

    @model_validator(mode="after")
    def _validate_data(self) -> WizardChartCreateDTO:
        _validate_wizard_v1_line_config(self.data)
        return self

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {"data": dict(self.data)}
        if self.key is not None:
            payload["key"] = self.key
        if self.name is not None:
            payload["name"] = self.name
        if self.workbook_id is not None:
            payload["workbookId"] = self.workbook_id
        if self.annotation is not None:
            payload["annotation"] = dict(self.annotation)
        return payload


class WizardChartUpdateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    chart_id: str = Field(serialization_alias="chartId")
    mode: Literal["save", "publish"]
    data: dict[str, JsonValue]
    annotation: dict[str, JsonValue] | None = None
    rev_id: str | None = Field(default=None, serialization_alias="revId")

    @model_validator(mode="after")
    def _validate_data(self) -> WizardChartUpdateDTO:
        _validate_wizard_v1_line_config(self.data)
        return self

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {
            "chartId": self.chart_id,
            "mode": self.mode,
            "data": dict(self.data),
        }
        if self.annotation is not None:
            payload["annotation"] = dict(self.annotation)
        if self.rev_id is not None:
            payload["revId"] = self.rev_id
        return payload


class WizardChartEntryReadDTO(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    version: Literal[1]
    entry_id: str = Field(alias="entryId")
    type: str | None = None
    data: dict[str, JsonValue]


class WizardChartReadDTO(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    entry: WizardChartEntryReadDTO
    raw: dict[str, JsonValue] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def _capture_raw(cls, value: object) -> object:
        if isinstance(value, dict) and "raw" not in value:
            return {**value, "raw": value}
        return value


class WizardChartGetArgsDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    chart_id: str = Field(serialization_alias="chartId")
    workbook_id: str | None = Field(default=None, serialization_alias="workbookId")

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {"chartId": self.chart_id}
        if self.workbook_id is not None:
            payload["workbookId"] = self.workbook_id
        return payload


class WizardChartDeleteArgsDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    chart_id: str = Field(serialization_alias="chartId")

    def to_payload(self) -> dict[str, object]:
        return {"chartId": self.chart_id}


class QLChartCreateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    template: Literal["ql"]
    data: Mapping[str, object]
    key: str | None = None
    name: str | None = None
    workbook_id: str | None = Field(default=None, serialization_alias="workbookId")
    annotation: Mapping[str, object] | None = None

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {
            "template": self.template,
            "data": dict(self.data),
        }
        if self.key is not None:
            payload["key"] = self.key
        if self.name is not None:
            payload["name"] = self.name
        if self.workbook_id is not None:
            payload["workbookId"] = self.workbook_id
        if self.annotation is not None:
            payload["annotation"] = dict(self.annotation)
        return payload


class QLChartUpdateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    entry_id: str = Field(serialization_alias="entryId")
    template: Literal["ql"]
    mode: Literal["save", "publish"]
    data: Mapping[str, object]
    annotation: Mapping[str, object] | None = None

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {
            "entryId": self.entry_id,
            "template": self.template,
            "mode": self.mode,
            "data": dict(self.data),
        }
        if self.annotation is not None:
            payload["annotation"] = dict(self.annotation)
        return payload


class QLChartReadDTO(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    entry_id: str | None = Field(default=None, alias="entryId")
    type: str | None = None
    data: dict[str, object] | None = None
    raw: dict[str, object] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def _capture_raw(cls, value: object) -> object:
        if isinstance(value, dict) and "raw" not in value:
            return {**value, "raw": dict(value)}
        return value


class QLChartGetArgsDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    chart_id: str = Field(serialization_alias="chartId")
    workbook_id: str | None = Field(default=None, serialization_alias="workbookId")

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {"chartId": self.chart_id}
        if self.workbook_id is not None:
            payload["workbookId"] = self.workbook_id
        return payload


class QLChartDeleteArgsDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    chart_id: str = Field(serialization_alias="chartId")

    def to_payload(self) -> dict[str, object]:
        return {"chartId": self.chart_id}

class AdvancedChartNodeNodeDataDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    controls: str
    meta: str
    params: str
    prepare: str
    sources: str

class AdvancedChartNodeNodeEntryCreateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    type: Literal['advanced-chart_node']
    data: AdvancedChartNodeNodeDataDTO
    key: str | None = None
    name: str | None = None
    workbook_id: str | None = Field(default=None, serialization_alias='workbookId')
    annotation: Mapping[str, object] | None = None
    links: Mapping[str, str] | None = None

    def to_payload(self) -> dict[str, object]:
        entry: dict[str, object] = {
            'type': 'advanced-chart_node',
            'data': self.data.model_dump(exclude_none=True),
        }
        if self.annotation is not None:
            entry['annotation'] = dict(self.annotation)
        if self.links is not None:
            entry['links'] = dict(self.links)
        if self.key is not None:
            entry['key'] = self.key
        if self.name is not None:
            entry['name'] = self.name
        if self.workbook_id is not None:
            entry['workbookId'] = self.workbook_id
        return {'entry': entry}

class ControlNodeNodeDataDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    controls: str
    meta: str
    params: str
    sources: str

class ControlNodeNodeEntryCreateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    type: Literal['control_node']
    data: ControlNodeNodeDataDTO
    key: str | None = None
    name: str | None = None
    workbook_id: str | None = Field(default=None, serialization_alias='workbookId')
    annotation: Mapping[str, object] | None = None
    links: Mapping[str, str] | None = None

    def to_payload(self) -> dict[str, object]:
        entry: dict[str, object] = {
            'type': 'control_node',
            'data': self.data.model_dump(exclude_none=True),
        }
        if self.annotation is not None:
            entry['annotation'] = dict(self.annotation)
        if self.links is not None:
            entry['links'] = dict(self.links)
        if self.key is not None:
            entry['key'] = self.key
        if self.name is not None:
            entry['name'] = self.name
        if self.workbook_id is not None:
            entry['workbookId'] = self.workbook_id
        return {'entry': entry}

class D3NodeNodeDataDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    config: str
    controls: str
    meta: str
    params: str
    prepare: str
    sources: str

class D3NodeNodeEntryCreateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    type: Literal['d3_node']
    data: D3NodeNodeDataDTO
    key: str | None = None
    name: str | None = None
    workbook_id: str | None = Field(default=None, serialization_alias='workbookId')
    annotation: Mapping[str, object] | None = None
    links: Mapping[str, str] | None = None

    def to_payload(self) -> dict[str, object]:
        entry: dict[str, object] = {
            'type': 'd3_node',
            'data': self.data.model_dump(exclude_none=True),
        }
        if self.annotation is not None:
            entry['annotation'] = dict(self.annotation)
        if self.links is not None:
            entry['links'] = dict(self.links)
        if self.key is not None:
            entry['key'] = self.key
        if self.name is not None:
            entry['name'] = self.name
        if self.workbook_id is not None:
            entry['workbookId'] = self.workbook_id
        return {'entry': entry}

class MarkdownNodeNodeDataDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    controls: str
    meta: str
    params: str
    prepare: str
    sources: str

class MarkdownNodeNodeEntryCreateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    type: Literal['markdown_node']
    data: MarkdownNodeNodeDataDTO
    key: str | None = None
    name: str | None = None
    workbook_id: str | None = Field(default=None, serialization_alias='workbookId')
    annotation: Mapping[str, object] | None = None
    links: Mapping[str, str] | None = None

    def to_payload(self) -> dict[str, object]:
        entry: dict[str, object] = {
            'type': 'markdown_node',
            'data': self.data.model_dump(exclude_none=True),
        }
        if self.annotation is not None:
            entry['annotation'] = dict(self.annotation)
        if self.links is not None:
            entry['links'] = dict(self.links)
        if self.key is not None:
            entry['key'] = self.key
        if self.name is not None:
            entry['name'] = self.name
        if self.workbook_id is not None:
            entry['workbookId'] = self.workbook_id
        return {'entry': entry}

class TableNodeNodeDataDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    config: str
    controls: str
    meta: str
    params: str
    prepare: str
    sources: str

class TableNodeNodeEntryCreateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    type: Literal['table_node']
    data: TableNodeNodeDataDTO
    key: str | None = None
    name: str | None = None
    workbook_id: str | None = Field(default=None, serialization_alias='workbookId')
    annotation: Mapping[str, object] | None = None
    links: Mapping[str, str] | None = None

    def to_payload(self) -> dict[str, object]:
        entry: dict[str, object] = {
            'type': 'table_node',
            'data': self.data.model_dump(exclude_none=True),
        }
        if self.annotation is not None:
            entry['annotation'] = dict(self.annotation)
        if self.links is not None:
            entry['links'] = dict(self.links)
        if self.key is not None:
            entry['key'] = self.key
        if self.name is not None:
            entry['name'] = self.name
        if self.workbook_id is not None:
            entry['workbookId'] = self.workbook_id
        return {'entry': entry}

class AdvancedChartNodeNodeUpdateDataDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    controls: str
    meta: str
    params: str
    prepare: str
    sources: str

class AdvancedChartNodeNodeEntryUpdateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    type: Literal['advanced-chart_node']
    entry_id: str = Field(serialization_alias='entryId')
    data: AdvancedChartNodeNodeUpdateDataDTO
    mode: Literal['save', 'publish']
    annotation: Mapping[str, object] | None = None
    links: Mapping[str, str] | None = None
    rev_id: str | None = Field(default=None, serialization_alias='revId')

    def to_payload(self) -> dict[str, object]:
        entry: dict[str, object] = {
            'type': 'advanced-chart_node',
            'entryId': self.entry_id,
            'data': self.data.model_dump(exclude_none=True),
        }
        if self.annotation is not None:
            entry['annotation'] = dict(self.annotation)
        if self.links is not None:
            entry['links'] = dict(self.links)
        if self.rev_id is not None:
            entry['revId'] = self.rev_id
        return {'entry': entry, 'mode': self.mode}

class ControlNodeNodeUpdateDataDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    controls: str
    meta: str
    params: str
    sources: str

class ControlNodeNodeEntryUpdateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    type: Literal['control_node']
    entry_id: str = Field(serialization_alias='entryId')
    data: ControlNodeNodeUpdateDataDTO
    mode: Literal['save', 'publish']
    annotation: Mapping[str, object] | None = None
    links: Mapping[str, str] | None = None
    rev_id: str | None = Field(default=None, serialization_alias='revId')

    def to_payload(self) -> dict[str, object]:
        entry: dict[str, object] = {
            'type': 'control_node',
            'entryId': self.entry_id,
            'data': self.data.model_dump(exclude_none=True),
        }
        if self.annotation is not None:
            entry['annotation'] = dict(self.annotation)
        if self.links is not None:
            entry['links'] = dict(self.links)
        if self.rev_id is not None:
            entry['revId'] = self.rev_id
        return {'entry': entry, 'mode': self.mode}

class D3NodeNodeUpdateDataDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    config: str
    controls: str
    meta: str
    params: str
    prepare: str
    sources: str

class D3NodeNodeEntryUpdateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    type: Literal['d3_node']
    entry_id: str = Field(serialization_alias='entryId')
    data: D3NodeNodeUpdateDataDTO
    mode: Literal['save', 'publish']
    annotation: Mapping[str, object] | None = None
    links: Mapping[str, str] | None = None
    rev_id: str | None = Field(default=None, serialization_alias='revId')

    def to_payload(self) -> dict[str, object]:
        entry: dict[str, object] = {
            'type': 'd3_node',
            'entryId': self.entry_id,
            'data': self.data.model_dump(exclude_none=True),
        }
        if self.annotation is not None:
            entry['annotation'] = dict(self.annotation)
        if self.links is not None:
            entry['links'] = dict(self.links)
        if self.rev_id is not None:
            entry['revId'] = self.rev_id
        return {'entry': entry, 'mode': self.mode}

class MarkdownNodeNodeUpdateDataDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    controls: str
    meta: str
    params: str
    prepare: str
    sources: str

class MarkdownNodeNodeEntryUpdateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    type: Literal['markdown_node']
    entry_id: str = Field(serialization_alias='entryId')
    data: MarkdownNodeNodeUpdateDataDTO
    mode: Literal['save', 'publish']
    annotation: Mapping[str, object] | None = None
    links: Mapping[str, str] | None = None
    rev_id: str | None = Field(default=None, serialization_alias='revId')

    def to_payload(self) -> dict[str, object]:
        entry: dict[str, object] = {
            'type': 'markdown_node',
            'entryId': self.entry_id,
            'data': self.data.model_dump(exclude_none=True),
        }
        if self.annotation is not None:
            entry['annotation'] = dict(self.annotation)
        if self.links is not None:
            entry['links'] = dict(self.links)
        if self.rev_id is not None:
            entry['revId'] = self.rev_id
        return {'entry': entry, 'mode': self.mode}

class TableNodeNodeUpdateDataDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    config: str
    controls: str
    meta: str
    params: str
    prepare: str
    sources: str

class TableNodeNodeEntryUpdateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    type: Literal['table_node']
    entry_id: str = Field(serialization_alias='entryId')
    data: TableNodeNodeUpdateDataDTO
    mode: Literal['save', 'publish']
    annotation: Mapping[str, object] | None = None
    links: Mapping[str, str] | None = None
    rev_id: str | None = Field(default=None, serialization_alias='revId')

    def to_payload(self) -> dict[str, object]:
        entry: dict[str, object] = {
            'type': 'table_node',
            'entryId': self.entry_id,
            'data': self.data.model_dump(exclude_none=True),
        }
        if self.annotation is not None:
            entry['annotation'] = dict(self.annotation)
        if self.links is not None:
            entry['links'] = dict(self.links)
        if self.rev_id is not None:
            entry['revId'] = self.rev_id
        return {'entry': entry, 'mode': self.mode}


class EditorChartReadDTO(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    entry_id: str | None = Field(default=None, alias="entryId")
    type: str | None = None
    data: dict[str, object] | None = None
    raw: dict[str, object] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def _capture_raw(cls, value: object) -> object:
        if isinstance(value, dict) and "raw" not in value:
            return {**value, "raw": value}
        return value


class EditorChartGetArgsDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    entry_id: str = Field(serialization_alias="entryId")
    workbook_id: str | None = Field(default=None, serialization_alias="workbookId")

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {"entryId": self.entry_id}
        if self.workbook_id is not None:
            payload["workbookId"] = self.workbook_id
        return payload


class EditorChartDeleteArgsDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    entry_id: str = Field(serialization_alias="entryId")

    def to_payload(self) -> dict[str, object]:
        return {"entryId": self.entry_id}


class DashboardCreateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    data: Mapping[str, object]
    # Required but nullable by the DashboardMeta schema: "meta": null must serialize.
    meta: Mapping[str, object] | None
    key: str | None = None
    name: str | None = None
    workbook_id: str | None = Field(default=None, serialization_alias="workbookId")
    annotation: Mapping[str, object] | None = None

    def to_payload(self) -> dict[str, object]:
        entry: dict[str, object] = {
            "data": dict(self.data),
            "meta": None if self.meta is None else dict(self.meta),
        }
        if self.annotation is not None:
            entry["annotation"] = dict(self.annotation)
        if self.key is not None:
            entry["key"] = self.key
        if self.name is not None:
            entry["name"] = self.name
        if self.workbook_id is not None:
            entry["workbookId"] = self.workbook_id
        return {"entry": entry}


class DashboardUpdateDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    entry_id: str = Field(serialization_alias="entryId")
    data: Mapping[str, object]
    # Required but nullable by the DashboardMeta schema: "meta": null must serialize.
    meta: Mapping[str, object] | None
    mode: Literal["save", "publish"]
    rev_id: str | None = Field(default=None, serialization_alias="revId")
    lock_token: str | None = Field(default=None, serialization_alias="lockToken")
    annotation: Mapping[str, object] | None = None

    def to_payload(self) -> dict[str, object]:
        entry: dict[str, object] = {
            "entryId": self.entry_id,
            "data": dict(self.data),
            "meta": None if self.meta is None else dict(self.meta),
        }
        if self.annotation is not None:
            entry["annotation"] = dict(self.annotation)
        if self.rev_id is not None:
            entry["revId"] = self.rev_id
        payload: dict[str, object] = {"entry": entry, "mode": self.mode}
        if self.lock_token is not None:
            payload["lockToken"] = self.lock_token
        return payload


class DashboardReadDTO(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    entry_id: str | None = Field(default=None, alias="entryId")
    key: str | None = None
    name: str | None = None
    data: dict[str, object] | None = None
    rev_id: str | None = Field(default=None, alias="revId")
    saved_id: str | None = Field(default=None, alias="savedId")
    published_id: str | None = Field(default=None, alias="publishedId")
    workbook_id: str | None = Field(default=None, alias="workbookId")
    raw: dict[str, object] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def _capture_raw(cls, value: object) -> object:
        if isinstance(value, dict) and "raw" not in value:
            return {**value, "raw": value}
        return value


class DashboardGetArgsDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    dashboard_id: str = Field(serialization_alias="dashboardId")
    workbook_id: str | None = Field(default=None, serialization_alias="workbookId")
    rev_id: str | None = Field(default=None, serialization_alias="revId")
    branch: Literal["saved", "published"] | None = None
    include_favorite: bool | None = Field(default=None, serialization_alias="includeFavorite")
    include_links: bool | None = Field(default=None, serialization_alias="includeLinks")
    include_permissions: bool | None = Field(default=None, serialization_alias="includePermissions")

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {"dashboardId": self.dashboard_id}
        if self.workbook_id is not None:
            payload["workbookId"] = self.workbook_id
        if self.rev_id is not None:
            payload["revId"] = self.rev_id
        if self.branch is not None:
            payload["branch"] = self.branch
        if self.include_favorite is not None:
            payload["includeFavorite"] = self.include_favorite
        if self.include_links is not None:
            payload["includeLinks"] = self.include_links
        if self.include_permissions is not None:
            payload["includePermissions"] = self.include_permissions
        return payload


class DashboardDeleteArgsDTO(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    dashboard_id: str = Field(serialization_alias="dashboardId")
    lock_token: str | None = Field(default=None, serialization_alias="lockToken")

    def to_payload(self) -> dict[str, object]:
        payload: dict[str, object] = {"dashboardId": self.dashboard_id}
        if self.lock_token is not None:
            payload["lockToken"] = self.lock_token
        return payload
